using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ArrestedDevelopmentApi.Migrations
{
    public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterDatabase()
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.CreateTable(
                name: "Quotes",
                columns: table => new
                {
                    QuoteId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    Speaker = table.Column<string>(type: "longtext", nullable: true)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    Text = table.Column<string>(type: "longtext", nullable: true)
                        .Annotation("MySql:CharSet", "utf8mb4")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Quotes", x => x.QuoteId);
                })
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.InsertData(
                table: "Quotes",
                columns: new[] { "QuoteId", "Speaker", "Text" },
                values: new object[,]
                {
                    { 1, "Unknown", "You boys know how to shovel coal?" },
                    { 2, "Buster", "What do you expect, Mother? I'm half machine!" },
                    { 3, "Buster", "I'm a monster!" },
                    { 4, "Unknown", "It's a good thing he's already got that little scooter" },
                    { 5, "Unknown", "A heart attack never stopped old Big Bear" },
                    { 6, "Buster", "I didn't even know we were calling him Big Bear" },
                    { 7, "Unknown", "You could charm the black off a telegram boy" },
                    { 8, "Unknown", "Did you see the new Poof?" },
                    { 9, "Lucille", "I love all of my children equally" },
                    { 10, "Unknown", "No one's called him Baby Buster since high school" },
                    { 11, "Unknown", "They didn't sneak into this country to be your friends" },
                    { 12, "Unknown", "You were just a turd out there, you know?" },
                    { 13, "Buster", "This party is going to be off the hook" },
                    { 14, "Unknown", "I hear the jury's still out on science" },
                    { 15, "Buster", "Like anyone would want to \"R\" her" },
                    { 16, "Buster", "Can't a guy call his mother pretty without it seeming strange?" },
                    { 17, "Unknown", "This is the best free scrapbooking class I've ever taken" },
                    { 18, "Unknown", "Go ahead, touch the Cornballer" },
                    { 19, "Buster", "I'm going to run this through again on \"pots and pans\"" },
                    { 20, "Tobias", "I've been in the film business for a while but I just can't seem to get one in the can" },
                    { 21, "Tobias", "I will be a bigger and hairier mole than the one on your inner left thigh" },
                    { 22, "Lucille", "I want to cry so bad, but I don't think I can spare the moisture" },
                    { 23, "GeorgeMichael", "Maybe it was the other George Michael" },
                    { 24, "Unknown", "I'm tired of trying to find happiness through lies and self-medicating" },
                    { 25, "Lindsay", "It's so watery, and yet there's a smack of ham to it" },
                    { 26, "Buster", "The seal is for marksmanship, and the gorilla is for sand racing" },
                    { 27, "Unknown", "After all these years, God's not going to take a call from you" },
                    { 28, "GOB", "You mean the guy we're meeting with can't even grow his own hair?" },
                    { 29, "Tobias", "I thought the two of us could talk man-on-man" },
                    { 30, "Tobias", "I spent so much time making sweet love on my wife that it's hard to hear anything over the clatter of her breasts" },
                    { 31, "Unknown", "You've been warned about touching" },
                    { 32, "Unknown", "No touching" },
                    { 33, "Unknown", "I think I maced a crane" },
                    { 34, "Lindsay", "Wine only turns to alcohol if you let it sit" },
                    { 35, "Tobias", "I see you've wasted no time in filling my seat hole" },
                    { 36, "GOB", "I'm going to buy you the single healthiest call girl this town has ever seen" },
                    { 37, "GOB", "Turn this skiff around" },
                    { 38, "Buster", "I never thought I'd miss a hand so much" },
                    { 39, "Tobias", "I can just taste those meaty leading man parts in my mouth." },
                    { 40, "Lucille", "Everyone's laughing and riding and cornholing except Buster" },
                    { 41, "Unknown", "You can always tell a Milford man" },
                    { 42, "Tobias", "Let me take off my assistant's skirt and put on my Barbra-Streisand-in-The-Prince-of-Tides ass-masking therapist pantsuit" },
                    { 43, "Franklin", "I don't want no part of yo tight-ass country-club" },
                    { 44, "Tobias", "Don't leave your Uncle T-Bag hanging" },
                    { 45, "Michael", "What have we always said is the most important thing?" },
                    { 46, "Buster", "We're just blowing through nap time, aren't we?" },
                    { 47, "Unknown", "Let me give that oatmeal some brown sugar" },
                    { 48, "Lucille", "A sea of waiters and no one will take a drink order" },
                    { 49, "Barry", "Those are balls" },
                    { 50, "Tobias", "I'm gonna build me an airport, put my name on it" },
                    { 51, "Tobias", "Let me out that queen" },
                    { 52, "Tobias", "Do these effectively hide my thunder?" },
                    { 53, "Buster", "You just grab that brownish area by its points and you don't let go no matter what your mother tells you" },
                    { 54, "Tobias", "I guess you can say I'm buy-curious" },
                    { 55, "Unknown", "The soup of the day is bread" },
                    { 56, "GeorgeMichael", "I could use a leather jacket for when I'm on my hog and have to go into a controlled slide" },
                    { 57, "Buster", "Are you at all concerned about an uprising?" },
                    { 58, "Tobias", "In the dark, it all looks the same" },
                    { 59, "Tobias", "Look at us, crying like a bunch of girls on the last day of camp" },
                    { 60, "Unknown", "You just made a fool out of yourself in front of T-Bone" },
                    { 61, "GOB", "I hope you also carry a spare bowl of candy beans" },
                    { 62, "Unknown", "You can't just comb that out and reset it?" },
                    { 63, "Lucille", "Look what the homosexuals have done to me" },
                    { 64, "Lucille", "Everything they do is so dramatic and flamboyant, it just makes me want to set myself on fire" },
                    { 65, "GeorgeSenior", "I may have committed some light treason" },
                    { 66, "Lucille", "I don't understand the question and I won't respond to it" },
                    { 67, "GeorgeSenior", "There's always money in the banana stand" },
                    { 68, "Tobias", "In this business of show, you have to have the heart of an angel and the hyde of an elephant" },
                    { 69, "GeorgeSenior", "Too many lives have been ruined because some cheap waitress at a HoJo said she used an I.U.D." },
                    { 70, "Buster", "Do you think I could have a hit of that juice box?" },
                    { 71, "Buster", "Suddenly he's too much of a big shot to brush Mother's hair" },
                    { 72, "Buster", "It walked on my pillow" },
                    { 73, "Michael", "That's not a spinner" },
                    { 74, "Buster", "I thought I saw a graham cracker out there" },
                    { 75, "CarlWeathers", "There's still plenty of meat on that bone" },
                    { 76, "CarlWeathers", "Now you take this home, throw it in a pot, add some broth, a potato" },
                    { 77, "CarlWeathers", "Baby, you got a stew going" },
                    { 78, "CarlWeathers", "Never once touched my per diem" },
                    { 79, "Buster", "Army had a half day" },
                    { 80, "Michael", "The mere fact that you call making love \"pop pop\" tells me that you're not ready" },
                    { 81, "Unknown", "I'd have to get up pretty early in the morning to get drunk by 1 o' clock" },
                    { 82, "Tobias", "There are dozens of us" },
                    { 83, "Michael", "I think you're going to be surprised at some of your phrasing" },
                    { 84, "GeorgeSenior", "Stop licking my hand, you horse's ass" },
                    { 85, "Tobias", "I'm afraid I just blue myself" },
                    { 86, "Lindsay", "Why don't we just take an ad out in \"I'm Poor\" magazine?" },
                    { 87, "Unknown", "And that's why you always leave a note" },
                    { 88, "Unknown", "It's not your fault your parents were cousins, but here we are" },
                    { 89, "Unknown", "You're going to get some hop-ons" },
                    { 90, "GOB", "It just seems like there's still light coming in from under the door" },
                    { 91, "Buster", "I'm leaving my mother for you" },
                    { 92, "Buster", "You're replacing my mother" },
                    { 93, "Tobias", "Even if it means me taking a chubby, I will suck it up" },
                    { 94, "Tobias", "If she's not going to say anything, I certainly can't help her" },
                    { 95, "Lucille", "I hate this doctor" },
                    { 96, "Unknown", "That's like comparing apples and some fruit nobody's ever heard of" },
                    { 97, "SteveHolt", "Is that what's going to happen to my hair?" },
                    { 98, "Unknown", "Finally, some good news from this guy" },
                    { 99, "Unknown", "There's no other way to take that" },
                    { 100, "Unknown", "He's lost his left hand, so he's going to be all right" },
                    { 101, "Tobias", "Perhaps an attic shall I seek" },
                    { 103, "Michael", "He's definitely got a type" },
                    { 104, "GOB", "That's my son, you pothead" },
                    { 105, "GOB", "God knows they're squinters" },
                    { 106, "Unknown", "Instead of making houses, maybe you should make land on the ocean" },
                    { 107, "Unknown", "Maybe you're not smart either. I didn't know until they told me" },
                    { 108, "Unknown", "I've opened a door here that I regret" },
                    { 109, "GOB", "What's Spanish for \"I know you speak English\"?" },
                    { 110, "Unknown", "You gave us cereal in an ashtray" },
                    { 111, "Franklin", "My name is Judge" },
                    { 112, "GeorgeSenior", "Why can't I have hair and money and him nothing?" },
                    { 113, "Tobias", "There's the woman I'm sexually attracted to" },
                    { 114, "Buster", "I was trained by Army" },
                    { 115, "Tobias", "I don't want to blame it all on 9/11, but it certainly didn't help" },
                    { 116, "Annyong", "Annyong" },
                    { 117, "Unknown", "Brand new cars don't get waxed" },
                    { 118, "Oscar", "Maybe I'll put it in her brownie" },
                    { 119, "Tobias", "You can sink your arrow into my buttocks any time" },
                    { 120, "Unknown", "I thought it was a pool toy" },
                    { 121, "Tobias", "I wouldn't mind kissing that man between the cheeks" },
                    { 122, "GOB", "Are those police boats?" },
                    { 124, "GOB", "Illusions, Michael" },
                    { 125, "Buster", "Clearly the blue part is the land" },
                    { 126, "Michael", "I don't know what I expected" },
                    { 127, "Tobias", "Huzzah!" },
                    { 128, "Tobias", "It's a wonderful restaurant" },
                    { 129, "Michael", "Why are you squeezing me with your body?" },
                    { 130, "Unknown", "He's going to be all right" },
                    { 131, "Unknown", "I was set up by the Brits" },
                    { 132, "Tobias", "Say something that will terrify me" },
                    { 133, "GOB", "I'll buy you a hundred George Michaels that you can teach to drive" },
                    { 134, "GOB", "I should be in this Poof" },
                    { 135, "TonyWonder", "Did somebody say Wonder?" },
                    { 136, "GOB", "She turns illusions for money" },
                    { 137, "Unknown", "Everything I've said about you can be covered with makeup and a lie about a thyroid problem" },
                    { 138, "Buster", "He just wants to see boys' Linuses" },
                    { 139, "Unknown", "Half your testicle was hanging out of that thing" },
                    { 140, "Unknown", "Give me an old pro like a Robert Redford" },
                    { 141, "Unknown", "Give my son the juice" },
                    { 142, "Lucille", "You look like the window of a butcher shop" },
                    { 143, "Buster", "You told me I wasn't fit to serve" },
                    { 144, "Buster", "They even touched my Charlie Browns" },
                    { 145, "Buster", "It's tired in here" },
                    { 146, "Buster", "Make love in your own hand, mother" },
                    { 147, "Buster", "Sometimes love should be terrifying" },
                    { 148, "Buster", "My Army training tells me that this is going to be a hot mission" },
                    { 151, "Buster", "Can't you keep my hand to yourself?" },
                    { 152, "Buster", "Have you seen my rubber hand?" },
                    { 153, "Buster", "I've always loved those leathery little snappy faces" },
                    { 154, "GOB", "Soft and alive" },
                    { 155, "Michael", "It wasn't really the pronunciation that bothered me" },
                    { 156, "Buster", "My hook is stuck in the stair car" },
                    { 157, "Unknown", "And that's why you don't use one-armed persons to teach lessons" },
                    { 158, "Unknown", "He's a robot!" },
                    { 159, "Buster", "If the only thing I could do was lay in bed all day and eat soup, I'd be happy" },
                    { 160, "Buster", "I could just take it through a tube" },
                    { 161, "Unknown", "Never let me die" },
                    { 162, "Unknown", "When I miss your lips, I'll put a fig in my mouth" },
                    { 163, "Buster", "My love thinks I'm a coward just because I wasted precious hospital resources to avoid my legal obligation" },
                    { 164, "Buster", "I've always pictured him in a lighthouse" },
                    { 165, "Unknown", "I need to be rubbing elbows, not working your fork" },
                    { 166, "Buster", "The ocean is my second biggest fear" },
                    { 167, "Lindsay", "I hope that's not a crack about my hair color, lips, forehead, nose and teeth because at least I'm not the wearing a round sweater set on my face" },
                    { 168, "Unknown", "You're looking at balls here" },
                    { 169, "GeorgeMichael", "I've seen the blood" },
                    { 170, "Unknown", "Imagine the impact if that had come on right when we turned on the TV" },
                    { 171, "Unknown", "Cool your Japanese jets" },
                    { 172, "Michael", "You forgot to say \"away\" again" },
                    { 173, "GOB", "Look at the beak on that bird" },
                    { 174, "Tobias", "I think the name Michael is making you look for a man" },
                    { 175, "Michael", "You can just say \"intercourse\"" },
                    { 176, "Michael", "We just say \"manager\"" },
                    { 177, "Michael", "Doesn't matter who" },
                    { 178, "Lucille", "I'd rather be dead in California than alive in Arizona" },
                    { 179, "Lindsay", "I call it hot ham water" },
                    { 180, "Unknown", "He's a regular Freddie Wilson, that one" },
                    { 181, "Michael", "Don't call it that" },
                    { 182, "Unknown", "If you didn't have adult onset diabetes, I wouldn't mind giving you a little sugar" },
                    { 183, "GOB", "You don't want a hungry dove down your pants" },
                    { 184, "GOB", "That's how Tony Wonder lost a nut" },
                    { 185, "GOB", "Why go to a banana stand when we can make YOUR banana stand?" },
                    { 186, "GOB", "Don't worry, these young beauties have been nowhere near the bananas" },
                    { 187, "GeorgeSenior", "And that's why you don't try to teach lessons to your father" },
                    { 188, "Unknown", "We'll be the laughing stock of the boardwalk" },
                    { 189, "GOB", "If you feel something moving down there, it's just the bird" },
                    { 190, "Unknown", "I might have you beaten with a pillowcase full of batteries" },
                    { 191, "Tobias", "The guy runs a prison; he can have any piece of ass he wants" },
                    { 192, "Michael", "Who's the \"her\" in that sentence?" },
                    { 193, "Michael", "Please don't call yourself that" },
                    { 194, "Unknown", "I don't know why I always assume that everyone has read my screenplay" },
                    { 195, "GOB", "I'm not going to spend this kind of money and not watch" },
                    { 196, "GOB", "He showers her with club sauce" },
                    { 197, "Michael", "You've never told me how many houses there are in the British Parliament" },
                    { 198, "Unknown", "I think we could be more than just gym buddies" },
                    { 199, "Tobias", "You're blowing my mind, Frank" },
                    { 200, "Unknown", "The whole backside has moles" },
                    { 201, "Tobias", "There's no \"I\" in \"win\"" },
                    { 202, "Tobias", "Within her lies a queen" },
                    { 203, "Unknown", "You can control your bladder when you're dead" },
                    { 204, "Tobias", "I ought to pull down your pants and spank your ass raw" },
                    { 205, "Unknown", "Why should you go to jail for a crime someone else noticed?" },
                    { 206, "Tobias", "I was a professional twice over: an analyst and a therapist" },
                    { 207, "Tobias", "The world's first analrapist" },
                    { 208, "Michael", "I shall drop you off alive, hooker or no" },
                    { 209, "Unknown", "They're polite and the men all sound gay, but they will rip out your heart" },
                    { 210, "Michael", "I almost had Pop-Pop in Reno" },
                    { 211, "Tobias", "If this tableau I recreate, perhaps I can re-snare my mate" },
                    { 212, "Unknown", "I don't want anybody to go inside that musty claptrap" },
                    { 213, "GOB", "We were both waiting for our dads at that garden where the little boy found the arm" },
                    { 214, "GOB", "I kind of feel like that kid who found the severed hand" },
                    { 215, "GOB", "I don't see you crying, robot" },
                    { 216, "Kitty", "Say goodbye to these" },
                    { 217, "Unknown", "I promised myself I wasn't going to become one of those people who were always going on about their screenplays" },
                    { 218, "Unknown", "Nobody sells any coke in this pen without daddy getting a taste" },
                    { 219, "Oscar", "You haven't seen a little box with a turtle on it, have you?" },
                    { 220, "Buster", "My turtle was living in it before he ate all the grass and died" },
                    { 221, "Tobias", "The scabs come right off" },
                    { 222, "Unknown", "I can't say no to the woman who gave me chlamydia" },
                    { 223, "Tobias", "People hear the name Tobias, they think big black guy" },
                    { 224, "GOB", "I just don't want people's kids getting their sticky little fingers all over these $2,600 pants" },
                    { 225, "GOB", "The guy who's dirty dancing with his niece is going to tell the guy in the $3,600 suit how to run the business. Come on" },
                    { 226, "Lucille", "Suddenly playing with yourself is a scholarly pursuit" },
                    { 227, "Lucille", "If I wanted something your thumb touched, I'd eat the inside of your ear" },
                    { 228, "Lucille", "You let him go in the sun?" },
                    { 229, "Lucille", "Then why don't you marry an ice cream sandwich?" },
                    { 230, "Buster", "I will pack your sweet pink mouth with so much ice cream you'll be the envy of every Jerry and Jane on the block" },
                    { 231, "GeorgeSenior", "I am having a love affair with this ice cream sandwich" },
                    { 232, "GeorgeSenior", "Did you stick it to her?" },
                    { 233, "GeorgeSenior", "Pop-Pop needs your hair" },
                    { 234, "Lucille", "At least he's in prison, not an urn" },
                    { 235, "Unknown", "You know the hair that no one's supposed to see?" },
                    { 236, "Unknown", "Everyone put on white robes and outsmarted us" },
                    { 237, "Tobias", "We shan't be telling your mother about this, shan't we?" },
                    { 238, "Unknown", "Now there's somebody who needs a good mother" },
                    { 239, "Lucille", "I'll leave when I'm good and ready" },
                    { 240, "Maeby", "I need one of those necklaces in the shape of a T" },
                    { 241, "Unknown", "There's a cream with real diamonds in it" },
                    { 242, "Tobias", "You, sir, are a mouthful" },
                    { 243, "GOB", "If I can't find a horny immigrant by then, I don't deserve to stay here" },
                    { 244, "Tobias", "There's a man inside me, and only when he's finally out can I walk free of pain" },
                    { 245, "Tobias", "I'm afraid I prematurely shot my wad on what was supposed to be a \"dry run\", if you will, so now I'm afraid I have something of a mess on my hands" },
                    { 246, "GOB", "I've made a huge mistake" },
                    { 247, "Tobias", "You are playing adults with fully-formed libidos, not two young men playing grab-ass in the shower" },
                    { 248, "GeorgeMichael", "I can't go on a million bike rides whenever you want me to" },
                    { 249, "GeorgeSenior", "The doctor said there were claw marks on the walls of her uterus" },
                    { 250, "Buster", "It's like she gets off on being withholding" },
                    { 251, "GOB", "Look who's ragging on the old lady" },
                    { 252, "Lucille", "Look at me, \"getting off\"" },
                    { 253, "Unknown", "I always ended up on all fours" },
                    { 254, "Tobias", "This kind of agility?" },
                    { 255, "Tobias", "Do you see me more as the respected dramatic actor or more of the beloved comic actor?" },
                    { 256, "GOB", "I don't even want to tell you what she wouldn't let me do to her in the car" },
                    { 257, "Buster", "I thought you had class" },
                    { 258, "Tobias", "Carl Weathers took everything from me" },
                    { 259, "Tobias", "You could have been sleeping with Frightened Inmate #2" },
                    { 260, "GeorgeMichael", "Some call me The Human Metronome" },
                    { 261, "GOB", "So far it's been all chain and no ball" },
                    { 262, "Unknown", "Not everything is strippers and booze and buckets of blood" },
                    { 263, "Unknown", "You're out of the band" },
                    { 264, "Buster", "I've already got a Lucille in my life" },
                    { 265, "Buster", "Is this something society will allow?" },
                    { 266, "Buster", "I just jumped through a plate glass window on a date" },
                    { 267, "Kitty", "I have been Googling your father" },
                    { 268, "Unknown", "I sold you for a pack of cigarettes" },
                    { 269, "GeorgeSenior", "You don't fire crazy" },
                    { 270, "GeorgeSenior", "All these books are cooked" },
                    { 271, "GeorgeMichael", "It's like a mind puzzle, an awesome mind puzzle" },
                    { 272, "GeorgeMichael", "Talk you off of what, Pop-Pop?" },
                    { 273, "GOB", "Where once there was a yacht, now there is naught" },
                    { 274, "GOB", "Who doesn't love the Jews?" },
                    { 275, "GeorgeMichael", "I was going to smoke the marijuana like a cigarette" },
                    { 276, "Michael", "They don't allow you to have bees in here" },
                    { 277, "Barry", "I think something laid eggs on me" },
                    { 278, "Annyong", "Mother say no carbohydrate for you if you ever going to get girlfriend that's not old lady" },
                    { 279, "Annyong", "Maybe we should kiss again to teach them a lesson about obvious" },
                    { 280, "Lucille", "Look how he zips now" },
                    { 281, "Unknown", "I should have never taken the pumps out of here" },
                    { 282, "GOB", "You just can't deal with the fact that I've got a super-thin wife with huge cans" },
                    { 283, "Unknown", "Did you know that you can get a refill on any drink you want here, and it's free?" },
                    { 284, "Unknown", "Aren't you the sweetest thing, spending some time with what's left of your uncle" },
                    { 285, "Unknown", "He couldn't wait to swoop in and throw on the sailor suit" },
                    { 286, "Unknown", "I got children all over town" },
                    { 287, "Buster", "My father is my uncle" },
                    { 288, "Unknown", "That's the kind of joke he would have loved" },
                    { 289, "Tobias", "Who'd like a banger in the mouth?" },
                    { 290, "Michael", "We just call it a sausage" },
                    { 291, "GOB", "Franklin said some things Whitey just wasn't ready to hear" },
                    { 292, "Tobias", "I forgot that we were in the colonies" },
                    { 293, "Unknown", "Take me to your secular world" },
                    { 294, "GOB", "My socks are wet" },
                    { 295, "GOB", "Me quick, want slow" },
                    { 296, "Unknown", "Tea for dong!" },
                    { 297, "Tobias", "I'd want to get in there and find some answers" },
                    { 298, "Tobias", "Excuse me for liking the way they shape my junk" },
                    { 299, "Ann", "It's not just going to be my love and George Michael's, but God's love as well" },
                    { 300, "Unknown", "Can it open a can?" },
                    { 301, "Unknown", "A seal didn't bite your Linus off, right?" },
                    { 302, "Unknown", "No, a seal didn't bite my Linus off" },
                    { 303, "GeorgeSenior", "Up yours, granny!" },
                    { 304, "Lucille", "You couldn't handle it!" },
                    { 305, "Tobias", "Seems like only yesterday you were bursting forth from your mother's fertile womb" },
                    { 306, "Maeby", "You don't see me nervous about being on my third Virgin Mary" },
                    { 307, "Lucille", "You are a worse psychiatrist than you are a son-in-law, and you will never get work as an actor because you have no talent" },
                    { 308, "Tobias", "I had no idea a ninety year-old man could cave in my chest cavity like that" },
                    { 309, "Tobias", "I think your knee is on my heart" },
                    { 310, "Tobias", "I'm afraid I prematurely shot my wad on what was supposed to be a dry run, if you will" },
                    { 311, "Lucille", "I'm going to see if I can get a wrench to strip my nuts" },
                    { 312, "GeorgeSenior", "I haven't had a massage since prison" },
                    { 313, "Lucille", "He's an alpaca" },
                    { 314, "GOB", "One of this guy's eyebrows just fell in the bowl of candy beans" },
                    { 315, "Michael", "I think George Michael is hiding Ann in the attic" },
                    { 316, "Michael", "It's as Ann as the nose on Plain's face" },
                    { 317, "GeorgeMichael", "I have Pop-Pop in the attic" },
                    { 318, "Tobias", "Who wants to go to the hospital?" },
                    { 319, "Tobias", "That was 100% inappropriate, and I do apologize profusely" },
                    { 320, "Buster", "I ought to point to Uncle Oscar's Charlie Browns next time you're on top of him, Mother" },
                    { 321, "Tobias", "I figured if I blue myself early I'd be nice and relaxed for a 9:00 dinner reservation" },
                    { 322, "Lindsay", "I can actually smear diamonds on my face, and it's only $400 a tub" },
                    { 323, "GeorgeMichael", "She calls it a 'mayon-egg'" },
                    { 324, "Buster", "Mom volunteered me for the Army just because the fat man dared her to" },
                    { 325, "GOB", "The tears just aren't coming" },
                    { 326, "Unknown", "You mean you can wear stripper clothes when you're not stripping?" },
                    { 327, "GeorgeSenior", "You could hump that hood" },
                    { 328, "GeorgeMichael", "What a fun sexy time for you" },
                    { 329, "Unknown", "What I'm calling you is a television actor" },
                    { 330, "Unknown", "There's only one man I've ever called a coward, and that's Brian Doyle Murray" },
                    { 331, "Unknown", "We do not wag our genitals at one another to make a point" },
                    { 332, "GOB", "It's a mainstay of the magician's toolkit, like how clowns always have a rag soaked in ether" },
                    { 333, "GOB", "The worst that could happen is that I could spill coffee all over this $3,000 suit" },
                    { 334, "Unknown", "I came out of you, he didn't" },
                    { 335, "Michael", "I liked it better when he just said Annyong" },
                    { 336, "GeorgeSenior", "Maybe it was the eleven months he spent in the womb" },
                    { 337, "Tobias", "You dont cry when you take those off?" },
                    { 338, "GeorgeSenior", "How many times I gotta tell this kid chicken wings?" },
                    { 339, "Tobias", "Somebody is a rude Gus" },
                    { 340, "GOB", "I can't even fake the death of a stripper" },
                    { 341, "GOB", "You didn't eat that dove, did you?" },
                    { 342, "Unknown", "If someone had left a note, this innocent man would still have his arm" },
                    { 343, "Unknown", "You'd think a man locked up in prison would able to abstain" },
                    { 344, "Lucille", "Your father with his disgusting tweaking" },
                    { 345, "Lucille", "I couldn't breast feed any of you kids because of that man" },
                    { 346, "Michael", "This is the nicest she's been since she found out that Rosa could breast-feed Buster" },
                    { 347, "GOB", "First you dump all over it, now you want to know how it's done" },
                    { 348, "Tobias", "I feel like the prettiest girl at the dance" },
                    { 349, "Tobias", "I need to go take down the buffet and set up the leather pony" },
                    { 350, "GeorgeSenior", "They cannot arrest a husband and wife for the same crime" },
                    { 351, "GeorgeMichael", "Say what you want about America - thirteen bucks can still get you a hell of a lot of mice" },
                    { 352, "GOB", "Who said anything bad about America?" },
                    { 353, "GeorgeMichael", "So I'm thinking of getting a motorcycle" },
                    { 354, "Maeby", "Your legs look exactly like mine, and I just shaved mine" },
                    { 355, "Tobias", "I'm looking for something that says \"Dad likes leather\"" },
                    { 356, "Tobias", "You have to be some sort of she-hulk to get this" },
                    { 357, "Buster", "Mom, you're ruining our fort" },
                    { 358, "Unknown", "Who'd want to mess with any of us?" },
                    { 359, "GeorgeMichael", "Trying to introduce some edge to the whole palette" },
                    { 360, "Lucille", "Is she the one who's going to take him to the dentist?" },
                    { 361, "UncleJack", "You're right inside me now" },
                    { 362, "Unknown", "I can't believe they wouldn't even give me a wheelchair ride" },
                    { 363, "Buster", "Doesn't this make you want to have an ice-cream cone?" },
                    { 364, "Buster", "I do believe there was some mention of some ice cream" },
                    { 365, "Buster", "Does anyone know how to eat one of these?" },
                    { 366, "Tobias", "There's a new daddy in town. A discipline daddy." },
                    { 367, "Unknown", "I tried hitchhiking, but it's hard to do without a thumb" },
                    { 368, "Tobias", "Now what we do is we paint our lips Joan Crawford red, pop on a little blue eyeliner and then plant a lipstick kiss on every one of them" },
                    { 369, "GOB", "Still, where'd the lighter fluid come from?" },
                    { 370, "Unknown", "Larry, go to a mirror" },
                    { 371, "Tobias", "Why am I not going under water?" },
                    { 372, "Unknown", "Why did I lose all the weight if they're going to put me in a pool cover?" },
                    { 373, "GeorgeMichael", "I wish I could draw her nose" },
                    { 374, "Tobias", "I just found out that my cellular telephone was a lemon" },
                    { 375, "Michael", "Are you wearing my dead wife's maternity clothes?" },
                    { 376, "Unknown", "I can't get this ham open" },
                    { 377, "Tobias", "If he's got a shot with her, just give me a little tap on the fanny" },
                    { 378, "GOB", "Now, when you do this without getting punched in the chest, you'll have more fun" },
                    { 379, "Tobias", "The Blue Man Group might need me, and I do deserve a fancy phone" },
                    { 380, "Lucille", "The doctor said I couldn't be a mother now if I tried" },
                    { 381, "Lindsay", "I'm much, much, much older than 15" },
                    { 382, "Unknown", "And the worst part is he thinks he's passing" },
                    { 383, "Unknown", "Wow, that does sound like a little girl" },
                    { 384, "Barry", "I'm going for a hot Ding Dong" },
                    { 385, "Lindsay", "She said “tingling” like 75 times" },
                    { 386, "Lucille", "You smell like a pine cone" },
                    { 387, "Unknown", "I'm on bad mushrooms" },
                    { 388, "Barry", "This close, they always look like landscape" },
                    { 389, "Unknown", "There were cutoffs up here?" },
                    { 390, "Lucille", "What are you doing with Mother's rape horn?" },
                    { 391, "Michael", "Do you want to steer, or are you too old to sit on your pop's lap and drive?" },
                    { 392, "Unknown", "They impounded my humble trailer" },
                    { 393, "Barry", "Does this look contagious to you?" },
                    { 394, "Tobias", "Nice to be back in a queen" },
                    { 395, "Tobias", "Let the great experiment begin" },
                    { 396, "Michael", "There's got to be a better way to say that" },
                    { 397, "GeorgeSenior", "I am having the time of my life" },
                    { 398, "Michael", "I haven't met Ann" },
                    { 399, "GeorgeMichael", "I kind of want to buy her a diamond" },
                    { 400, "Michael", "I'm sure that Egg is a very nice person" },
                    { 401, "Buster", "I heard zoo noises" },
                    { 402, "Unknown", "Which pinky do you use less?" },
                    { 403, "GOB", "Nothing on the inside" },
                    { 404, "Lindsay", "I'm not proud of the way I was so grossed out when I found out you were gross before" },
                    { 405, "Buster", "I'm just hoping to get mildly injured so I can get out of the Army" },
                    { 406, "Unknown", "I think my nipples are bleeding" },
                    { 407, "Unknown", "Flashes of Quincy" },
                    { 408, "GOB", "I think the plant lady's wearing a thong" },
                    { 409, "Unknown", "Don't be such an Ann hog" },
                    { 410, "Lucille", "Go see a Star War" },
                    { 411, "Unknown", "Why am I not blacking out?" },
                    { 412, "Unknown", "He swore by that Glisten" },
                    { 413, "Unknown", "Let's go dig up your uncle" },
                    { 414, "Unknown", "I will be head to toe in blue makeup until 8:01 in case the Blue Man Group needs their understudy" },
                    { 415, "Unknown", "Are we having yams?" },
                    { 416, "Unknown", "First I blow him, then I poke him" },
                    { 417, "Unknown", "I don't think we need people trying to compete with what I'm wearing" },
                    { 418, "Unknown", "Don't ask me, I'm just the boy's father" },
                    { 419, "Lucille", "No one would believe that a woman like me would have a gay son" },
                    { 420, "Unknown", "I can see marinating a chicken in that" },
                    { 421, "Unknown", "Your Tweety Bird dance just cost us a run, you moron" },
                    { 422, "GOB", "How do we filter out the teases? We don't let them in." },
                    { 423, "Unknown", "I am stable as a table" },
                    { 424, "Unknown", "I would hardly call my mother a girl, but yes, she's still very much a part of my life" },
                    { 425, "Unknown", "Everybody thinks they're Frank Sinatra" },
                    { 426, "Unknown", "They make me feel dressier" },
                    { 427, "Unknown", "A piano could stand on those legs" },
                    { 428, "GeorgeMichael", "Guess she didn't see the drawings" },
                    { 429, "Unknown", "You have undone all of Dr. Sandor Plumb's work" },
                    { 430, "Tobias", "I need to prove to her that I'm not just a man, but a man's man" },
                    { 431, "Unknown", "Shall I put the Posturepedic in the down position?" },
                    { 432, "Unknown", "Read me the appetizers again" },
                    { 433, "Unknown", "Did you have too much club sauce on your calamari?" },
                    { 434, "GeorgeSenior", "I tried to drink some of the water, and it was too hot and it tasted like soy sauce" },
                    { 435, "GeorgeSenior", "I think the teriyaki chicken burst" },
                    { 436, "GeorgeSenior", "This isn't turning into the party hangout I hoped" },
                    { 437, "Lindsay", "Stick a wrench in me, I'm done" },
                    { 438, "UncleJack", "Someone order 140 pounds of upper-body strength?" },
                    { 439, "UncleJack", "It's just something the body does when you shake it" },
                    { 440, "Maeby", "Well, I'm all grown up now" },
                    { 441, "UncleJack", "How'd you like to take a nap, baldy?" },
                    { 442, "Michael", "Let's not spin in the comfy chair" },
                    { 443, "Barry", "I got Michael out of his marriage, didn't I?" },
                    { 444, "Barry", "I need macaroons" },
                    { 445, "Unknown", "You can win every argument like that, but that does not make you right" },
                    { 446, "Unknown", "I really hate it when you put on the God costume" },
                    { 447, "Unknown", "I'm cloaking myself in her scent" },
                    { 448, "Buster", "I was made to understand that there would be grilled cheese sandwiches here" },
                    { 449, "Buster", "Will someone please have the decency to punch me in the face?" },
                    { 450, "Buster", "Mom always taught us to curl up in a ball and remain motionless when confronted" },
                    { 451, "Buster", "We have unlimited juice?" },
                    { 453, "Unknown", "We all know you're Annyong" },
                    { 454, "Buster", "No, Mother, I can blow myself" },
                    { 455, "Michael", "Her?" },
                    { 456, "Unknown", "She was made in a cup, like soup" },
                    { 457, "Tobias", "Oh, I'm sorry, I forgot: your wife is dead" },
                    { 458, "Unknown", "The one thing I will never do is not tell him that I'm taking him to a cabin in the woods and then not take him" },
                    { 459, "GeorgeSenior", "He was our miracle baby" },
                    { 460, "GOB", "It's like my heart is getting hard" },
                    { 461, "GOB", "I know what an erection feels like, Michael" },
                    { 462, "Unknown", "Those aren't even birds" },
                    { 463, "GOB", "But I'm white" },
                    { 464, "GOB", "It ain't easy being white" },
                    { 465, "Buster", "I'm Mom and I want to shoot down everything you say so I feel good about myself" },
                    { 466, "Unknown", "Lets deal some drugs" },
                    { 467, "Unknown", "Why do you think I wear these?" },
                    { 468, "GOB", "A magician never reveals his secrets" },
                    { 469, "Unknown", "When's that voice gonna drop?" },
                    { 470, "Maeby", "I'm gonna go get sexy" },
                    { 471, "Lucille", "They said he was some kind of scientist" },
                    { 472, "Michael", "Speaking of settling, How's Ann?" },
                    { 473, "GeorgeSenior", "It's hard to gauge time" },
                    { 474, "GeorgeMichael", "I like the way they think" },
                    { 475, "GeorgeMichael", "I was hoping he would be gifted sexually" },
                    { 476, "Tobias", "If this were a Lifetime Moment of Truth movie, this would be our act break" },
                    { 477, "Unknown", "A flower in my garden, a mystery in my panties" },
                    { 478, "Buster", "I'm a scholar. I enjoy scholarly pursuits" },
                    { 479, "Unknown", "The warden could easily be black" },
                    { 480, "Tobias", "Who is this shiny building of a man?" },
                    { 481, "Buster", "Chickens don't clap" },
                    { 482, "Unknown", "I've got a stair car full of Mexican laborers that would love a day's work" },
                    { 483, "Unknown", "Are beads cheap?" },
                    { 484, "Unknown", "We'll see who brings in more honey" },
                    { 485, "Michael", "He's thinking about bees again" },
                    { 486, "Unknown", "We're going to have to figure out something to do so that people can look at you without wanting to kill themselves" },
                    { 487, "GOB", "You don’t know a good bird hospital, do you?" },
                    { 488, "GOB", "Hair up, glasses off" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Quotes");
        }
    }
}
