using Microsoft.EntityFrameworkCore;

namespace ArrestedDevelopmentApi.Models
{
  public class ArrestedDevelopmentApiContext : DbContext
  {
    public DbSet<Quote> Quotes { get; set; }

    public ArrestedDevelopmentApiContext(DbContextOptions<ArrestedDevelopmentApiContext> options) : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder builder)
    {
      builder.Entity<Quote>().HasData(
        new Quote { QuoteId = 1, Speaker = "Unknown", Text = "You boys know how to shovel coal?" },
        new Quote { QuoteId = 2, Speaker = "Buster", Text = "What do you expect, Mother? I'm half machine!" },
        new Quote { QuoteId = 3, Speaker = "Buster", Text = "I'm a monster!" },
        new Quote { QuoteId = 4, Speaker = "Unknown", Text = "It's a good thing he's already got that little scooter" },
        new Quote { QuoteId = 5, Speaker = "Unknown", Text = "A heart attack never stopped old Big Bear" },
        new Quote { QuoteId = 6, Speaker = "Buster", Text = "I didn't even know we were calling him Big Bear" },
        new Quote { QuoteId = 7, Speaker = "Unknown", Text = "You could charm the black off a telegram boy" },
        new Quote { QuoteId = 8, Speaker = "Unknown", Text = "Did you see the new Poof?" },
        new Quote { QuoteId = 9, Speaker = "Lucille", Text = "I love all of my children equally" },
        new Quote { QuoteId = 10, Speaker = "Unknown", Text = "No one's called him Baby Buster since high school" },
        new Quote { QuoteId = 11, Speaker = "Unknown", Text = "They didn't sneak into this country to be your friends" },
        new Quote { QuoteId = 12, Speaker = "Unknown", Text = "You were just a turd out there, you know?" },
        new Quote { QuoteId = 13, Speaker = "Buster", Text = "This party is going to be off the hook" },
        new Quote { QuoteId = 14, Speaker = "Unknown", Text = "I hear the jury's still out on science" },
        new Quote { QuoteId = 15, Speaker = "Buster", Text = "Like anyone would want to \"R\" her" },
        new Quote { QuoteId = 16, Speaker = "Buster", Text = "Can't a guy call his mother pretty without it seeming strange?" },
        new Quote { QuoteId = 17, Speaker = "Unknown", Text = "This is the best free scrapbooking class I've ever taken" },
        new Quote { QuoteId = 18, Speaker = "Unknown", Text = "Go ahead, touch the Cornballer" },
        new Quote { QuoteId = 19, Speaker = "Buster", Text = "I'm going to run this through again on \"pots and pans\"" },
        new Quote { QuoteId = 20, Speaker = "Tobias", Text = "I've been in the film business for a while but I just can't seem to get one in the can" },
        new Quote { QuoteId = 21, Speaker = "Tobias", Text = "I will be a bigger and hairier mole than the one on your inner left thigh" },
        new Quote { QuoteId = 22, Speaker = "Lucille", Text = "I want to cry so bad, but I don't think I can spare the moisture" },
        new Quote { QuoteId = 23, Speaker = "GeorgeMichael", Text = "Maybe it was the other George Michael" },
        new Quote { QuoteId = 24, Speaker = "Unknown", Text = "I'm tired of trying to find happiness through lies and self-medicating" },
        new Quote { QuoteId = 25, Speaker = "Lindsay", Text = "It's so watery, and yet there's a smack of ham to it" },
        new Quote { QuoteId = 26, Speaker = "Buster", Text = "The seal is for marksmanship, and the gorilla is for sand racing" },
        new Quote { QuoteId = 27, Speaker = "Unknown", Text = "After all these years, God's not going to take a call from you" },
        new Quote { QuoteId = 28, Speaker = "GOB", Text = "You mean the guy we're meeting with can't even grow his own hair?" },
        new Quote { QuoteId = 29, Speaker = "Tobias", Text = "I thought the two of us could talk man-on-man" },
        new Quote { QuoteId = 30, Speaker = "Tobias", Text = "I spent so much time making sweet love on my wife that it's hard to hear anything over the clatter of her breasts" },
        new Quote { QuoteId = 31, Speaker = "Unknown", Text = "You've been warned about touching" },
        new Quote { QuoteId = 32, Speaker = "Unknown", Text = "No touching" },
        new Quote { QuoteId = 33, Speaker = "Unknown", Text = "I think I maced a crane" },
        new Quote { QuoteId = 34, Speaker = "Lindsay", Text = "Wine only turns to alcohol if you let it sit" },
        new Quote { QuoteId = 35, Speaker = "Tobias", Text = "I see you've wasted no time in filling my seat hole" },
        new Quote { QuoteId = 36, Speaker = "GOB", Text = "I'm going to buy you the single healthiest call girl this town has ever seen" },
        new Quote { QuoteId = 37, Speaker = "GOB", Text = "Turn this skiff around" },
        new Quote { QuoteId = 38, Speaker = "Buster", Text = "I never thought I'd miss a hand so much" },
        new Quote { QuoteId = 39, Speaker = "Tobias", Text = "I can just taste those meaty leading man parts in my mouth." },
        new Quote { QuoteId = 40, Speaker = "Lucille", Text = "Everyone's laughing and riding and cornholing except Buster" },
        new Quote { QuoteId = 41, Speaker = "Unknown", Text = "You can always tell a Milford man" },
        new Quote { QuoteId = 42, Speaker = "Tobias", Text = "Let me take off my assistant's skirt and put on my Barbra-Streisand-in-The-Prince-of-Tides ass-masking therapist pantsuit" },
        new Quote { QuoteId = 43, Speaker = "Franklin", Text = "I don't want no part of yo tight-ass country-club" },
        new Quote { QuoteId = 44, Speaker = "Tobias", Text = "Don't leave your Uncle T-Bag hanging" },
        new Quote { QuoteId = 45, Speaker = "Michael", Text = "What have we always said is the most important thing?" },
        new Quote { QuoteId = 46, Speaker = "Buster", Text = "We're just blowing through nap time, aren't we?" },
        new Quote { QuoteId = 47, Speaker = "Unknown", Text = "Let me give that oatmeal some brown sugar" },
        new Quote { QuoteId = 48, Speaker = "Lucille", Text = "A sea of waiters and no one will take a drink order" },
        new Quote { QuoteId = 49, Speaker = "Barry", Text = "Those are balls" },
        new Quote { QuoteId = 50, Speaker = "Tobias", Text = "I'm gonna build me an airport, put my name on it" },
        new Quote { QuoteId = 51, Speaker = "Tobias", Text = "Let me out that queen" },
        new Quote { QuoteId = 52, Speaker = "Tobias", Text = "Do these effectively hide my thunder?" },
        new Quote { QuoteId = 53, Speaker = "Buster", Text = "You just grab that brownish area by its points and you don't let go no matter what your mother tells you" },
        new Quote { QuoteId = 54, Speaker = "Tobias", Text = "I guess you can say I'm buy-curious" },
        new Quote { QuoteId = 55, Speaker = "Unknown", Text = "The soup of the day is bread" },
        new Quote { QuoteId = 56, Speaker = "GeorgeMichael", Text = "I could use a leather jacket for when I'm on my hog and have to go into a controlled slide" },
        new Quote { QuoteId = 57, Speaker = "Buster", Text = "Are you at all concerned about an uprising?" },
        new Quote { QuoteId = 58, Speaker = "Tobias", Text = "In the dark, it all looks the same" },
        new Quote { QuoteId = 59, Speaker = "Tobias", Text = "Look at us, crying like a bunch of girls on the last day of camp" },
        new Quote { QuoteId = 60, Speaker = "Unknown", Text = "You just made a fool out of yourself in front of T-Bone" },
        new Quote { QuoteId = 61, Speaker = "GOB", Text = "I hope you also carry a spare bowl of candy beans" },
        new Quote { QuoteId = 62, Speaker = "Unknown", Text = "You can't just comb that out and reset it?" },
        new Quote { QuoteId = 63, Speaker = "Lucille", Text = "Look what the homosexuals have done to me" },
        new Quote { QuoteId = 64, Speaker = "Lucille", Text = "Everything they do is so dramatic and flamboyant, it just makes me want to set myself on fire" },
        new Quote { QuoteId = 65, Speaker = "GeorgeSenior", Text = "I may have committed some light treason" },
        new Quote { QuoteId = 66, Speaker = "Lucille", Text = "I don't understand the question and I won't respond to it" },
        new Quote { QuoteId = 67, Speaker = "GeorgeSenior", Text = "There's always money in the banana stand" },
        new Quote { QuoteId = 68, Speaker = "Tobias", Text = "In this business of show, you have to have the heart of an angel and the hyde of an elephant" },
        new Quote { QuoteId = 69, Speaker = "GeorgeSenior", Text = "Too many lives have been ruined because some cheap waitress at a HoJo said she used an I.U.D." },
        new Quote { QuoteId = 70, Speaker = "Buster", Text = "Do you think I could have a hit of that juice box?" },
        new Quote { QuoteId = 71, Speaker = "Buster", Text = "Suddenly he's too much of a big shot to brush Mother's hair" },
        new Quote { QuoteId = 72, Speaker = "Buster", Text = "It walked on my pillow" },
        new Quote { QuoteId = 73, Speaker = "Michael", Text = "That's not a spinner" },
        new Quote { QuoteId = 74, Speaker = "Buster", Text = "I thought I saw a graham cracker out there" },
        new Quote { QuoteId = 75, Speaker = "CarlWeathers", Text = "There's still plenty of meat on that bone" },
        new Quote { QuoteId = 76, Speaker = "CarlWeathers", Text = "Now you take this home, throw it in a pot, add some broth, a potato" },
        new Quote { QuoteId = 77, Speaker = "CarlWeathers", Text = "Baby, you got a stew going" },
        new Quote { QuoteId = 78, Speaker = "CarlWeathers", Text = "Never once touched my per diem" },
        new Quote { QuoteId = 79, Speaker = "Buster", Text = "Army had a half day" },
        new Quote { QuoteId = 80, Speaker = "Michael", Text = "The mere fact that you call making love \"pop pop\" tells me that you're not ready" },
        new Quote { QuoteId = 81, Speaker = "Unknown", Text = "I'd have to get up pretty early in the morning to get drunk by 1 o' clock" },
        new Quote { QuoteId = 82, Speaker = "Tobias", Text = "There are dozens of us" },
        new Quote { QuoteId = 83, Speaker = "Michael", Text = "I think you're going to be surprised at some of your phrasing" },
        new Quote { QuoteId = 84, Speaker = "GeorgeSenior", Text = "Stop licking my hand, you horse's ass" },
        new Quote { QuoteId = 85, Speaker = "Tobias", Text = "I'm afraid I just blue myself" },
        new Quote { QuoteId = 86, Speaker = "Lindsay", Text = "Why don't we just take an ad out in \"I\'m Poor\" magazine?" },
        new Quote { QuoteId = 87, Speaker = "Unknown", Text = "And that's why you always leave a note" },
        new Quote { QuoteId = 88, Speaker = "Unknown", Text = "It's not your fault your parents were cousins, but here we are" },
        new Quote { QuoteId = 89, Speaker = "Unknown", Text = "You're going to get some hop-ons" },
        new Quote { QuoteId = 90, Speaker = "GOB", Text = "It just seems like there's still light coming in from under the door" },
        new Quote { QuoteId = 91, Speaker = "Buster", Text = "I'm leaving my mother for you" },
        new Quote { QuoteId = 92, Speaker = "Buster", Text = "You're replacing my mother" },
        new Quote { QuoteId = 93, Speaker = "Tobias", Text = "Even if it means me taking a chubby, I will suck it up" },
        new Quote { QuoteId = 94, Speaker = "Tobias", Text = "If she's not going to say anything, I certainly can't help her" },
        new Quote { QuoteId = 95, Speaker = "Lucille", Text = "I hate this doctor" },
        new Quote { QuoteId = 96, Speaker = "Unknown", Text = "That's like comparing apples and some fruit nobody's ever heard of" },
        new Quote { QuoteId = 97, Speaker = "SteveHolt", Text = "Is that what's going to happen to my hair?" },
        new Quote { QuoteId = 98, Speaker = "Unknown", Text = "Finally, some good news from this guy" },
        new Quote { QuoteId = 99, Speaker = "Unknown", Text = "There's no other way to take that" },
        new Quote { QuoteId = 100, Speaker = "Unknown", Text = "He's lost his left hand, so he's going to be all right" },
        new Quote { QuoteId = 101, Speaker = "Tobias", Text = "Perhaps an attic shall I seek" },
        new Quote { QuoteId = 102, Speaker = "GOB", Text = "Don't call my escorts whores" },
        new Quote { QuoteId = 103, Speaker = "Michael", Text = "He's definitely got a type" },
        new Quote { QuoteId = 104, Speaker = "GOB", Text = "That's my son, you pothead" },
        new Quote { QuoteId = 105, Speaker = "GOB", Text = "God knows they're squinters" },
        new Quote { QuoteId = 106, Speaker = "Unknown", Text = "Instead of making houses, maybe you should make land on the ocean" },
        new Quote { QuoteId = 107, Speaker = "Unknown", Text = "Maybe you're not smart either. I didn't know until they told me" },
        new Quote { QuoteId = 108, Speaker = "Unknown", Text = "I've opened a door here that I regret" },
        new Quote { QuoteId = 109, Speaker = "GOB", Text = "What's Spanish for \"I know you speak English\"?" },
        new Quote { QuoteId = 110, Speaker = "Unknown", Text = "You gave us cereal in an ashtray" },
        new Quote { QuoteId = 111, Speaker = "Franklin", Text = "My name is Judge" },
        new Quote { QuoteId = 112, Speaker = "GeorgeSenior", Text = "Why can't I have hair and money and him nothing?" },
        new Quote { QuoteId = 113, Speaker = "Tobias", Text = "There's the woman I'm sexually attracted to" },
        new Quote { QuoteId = 114, Speaker = "Buster", Text = "I was trained by Army" },
        new Quote { QuoteId = 115, Speaker = "Tobias", Text = "I don't want to blame it all on 9/11, but it certainly didn't help" },
        new Quote { QuoteId = 116, Speaker = "Annyong", Text = "Annyong" },
        new Quote { QuoteId = 117, Speaker = "Unknown", Text = "Brand new cars don't get waxed" },
        new Quote { QuoteId = 118, Speaker = "Oscar", Text = "Maybe I'll put it in her brownie" },
        new Quote { QuoteId = 119, Speaker = "Tobias", Text = "You can sink your arrow into my buttocks any time" },
        new Quote { QuoteId = 120, Speaker = "Unknown", Text = "I thought it was a pool toy" },
        new Quote { QuoteId = 121, Speaker = "Tobias", Text = "I wouldn't mind kissing that man between the cheeks" },
        new Quote { QuoteId = 122, Speaker = "GOB", Text = "Are those police boats?" },
        new Quote { QuoteId = 123, Speaker = "GOB", Text = "A trick is something a whore does for money" },
        new Quote { QuoteId = 124, Speaker = "GOB", Text = "Illusions, Michael" },
        new Quote { QuoteId = 125, Speaker = "Buster", Text = "Clearly the blue part is the land" },
        new Quote { QuoteId = 126, Speaker = "Michael", Text = "I don't know what I expected" },
        new Quote { QuoteId = 127, Speaker = "Tobias", Text = "Huzzah!" },
        new Quote { QuoteId = 128, Speaker = "Tobias", Text = "It's a wonderful restaurant" },
        new Quote { QuoteId = 129, Speaker = "Michael", Text = "Why are you squeezing me with your body?" },
        new Quote { QuoteId = 130, Speaker = "Unknown", Text = "He's going to be all right" },
        new Quote { QuoteId = 131, Speaker = "Unknown", Text = "I was set up by the Brits" },
        new Quote { QuoteId = 132, Speaker = "Tobias", Text = "Say something that will terrify me" },
        new Quote { QuoteId = 133, Speaker = "GOB", Text = "I'll buy you a hundred George Michaels that you can teach to drive" },
        new Quote { QuoteId = 134, Speaker = "GOB", Text = "I should be in this Poof" },
        new Quote { QuoteId = 135, Speaker = "TonyWonder", Text = "Did somebody say Wonder?" },
        new Quote { QuoteId = 136, Speaker = "GOB", Text = "She turns illusions for money" },
        new Quote { QuoteId = 137, Speaker = "Unknown", Text = "Everything I've said about you can be covered with makeup and a lie about a thyroid problem" },
        new Quote { QuoteId = 138, Speaker = "Buster", Text = "He just wants to see boys' Linuses" },
        new Quote { QuoteId = 139, Speaker = "Unknown", Text = "Half your testicle was hanging out of that thing" },
        new Quote { QuoteId = 140, Speaker = "Unknown", Text = "Give me an old pro like a Robert Redford" },
        new Quote { QuoteId = 141, Speaker = "Unknown", Text = "Give my son the juice" },
        new Quote { QuoteId = 142, Speaker = "Lucille", Text = "You look like the window of a butcher shop" },
        new Quote { QuoteId = 143, Speaker = "Buster", Text = "You told me I wasn't fit to serve" },
        new Quote { QuoteId = 144, Speaker = "Buster", Text = "They even touched my Charlie Browns" },
        new Quote { QuoteId = 145, Speaker = "Buster", Text = "It's tired in here" },
        new Quote { QuoteId = 146, Speaker = "Buster", Text = "Make love in your own hand, mother" },
        new Quote { QuoteId = 147, Speaker = "Buster", Text = "Sometimes love should be terrifying" },
        new Quote { QuoteId = 148, Speaker = "Buster", Text = "My Army training tells me that this is going to be a hot mission" },
        new Quote { QuoteId = 149, Speaker = "GOB", Text = "I don't date whores" },
        new Quote { QuoteId = 150, Speaker = "GOB", Text = "It's just mom and whores" },
        new Quote { QuoteId = 151, Speaker = "Buster", Text = "Can't you keep my hand to yourself?" },
        new Quote { QuoteId = 152, Speaker = "Buster", Text = "Have you seen my rubber hand?" },
        new Quote { QuoteId = 153, Speaker = "Buster", Text = "I've always loved those leathery little snappy faces" },
        new Quote { QuoteId = 154, Speaker = "GOB", Text = "Soft and alive" },
        new Quote { QuoteId = 155, Speaker = "Michael", Text = "It wasn't really the pronunciation that bothered me" },
        new Quote { QuoteId = 156, Speaker = "Buster", Text = "My hook is stuck in the stair car" },
        new Quote { QuoteId = 157, Speaker = "Unknown", Text = "And that's why you don't use one-armed persons to teach lessons" },
        new Quote { QuoteId = 158, Speaker = "Unknown", Text = "He's a robot!" },
        new Quote { QuoteId = 159, Speaker = "Buster", Text = "If the only thing I could do was lay in bed all day and eat soup, I'd be happy" },
        new Quote { QuoteId = 160, Speaker = "Buster", Text = "I could just take it through a tube" },
        new Quote { QuoteId = 161, Speaker = "Unknown", Text = "Never let me die" },
        new Quote { QuoteId = 162, Speaker = "Unknown", Text = "When I miss your lips, I'll put a fig in my mouth" },
        new Quote { QuoteId = 163, Speaker = "Buster", Text = "My love thinks I'm a coward just because I wasted precious hospital resources to avoid my legal obligation" },
        new Quote { QuoteId = 164, Speaker = "Buster", Text = "I've always pictured him in a lighthouse" },
        new Quote { QuoteId = 165, Speaker = "Unknown", Text = "I need to be rubbing elbows, not working your fork" },
        new Quote { QuoteId = 166, Speaker = "Buster", Text = "The ocean is my second biggest fear" },
        new Quote { QuoteId = 167, Speaker = "Lindsay", Text = "I hope that's not a crack about my hair color, lips, forehead, nose and teeth because at least I'm not the wearing a round sweater set on my face" },
        new Quote { QuoteId = 168, Speaker = "Unknown", Text = "You're looking at balls here" },
        new Quote { QuoteId = 169, Speaker = "GeorgeMichael", Text = "I've seen the blood" },
        new Quote { QuoteId = 170, Speaker = "Unknown", Text = "Imagine the impact if that had come on right when we turned on the TV" },
        new Quote { QuoteId = 171, Speaker = "Unknown", Text = "Cool your Japanese jets" },
        new Quote { QuoteId = 172, Speaker = "Michael", Text = "You forgot to say \"away\" again" },
        new Quote { QuoteId = 173, Speaker = "GOB", Text = "Look at the beak on that bird" },
        new Quote { QuoteId = 174, Speaker = "Tobias", Text = "I think the name Michael is making you look for a man" },
        new Quote { QuoteId = 175, Speaker = "Michael", Text = "You can just say \"intercourse\"" },
        new Quote { QuoteId = 176, Speaker = "Michael", Text = "We just say \"manager\"" },
        new Quote { QuoteId = 177, Speaker = "Michael", Text = "Doesn't matter who" },
        new Quote { QuoteId = 178, Speaker = "Lucille", Text = "I'd rather be dead in California than alive in Arizona" },
        new Quote { QuoteId = 179, Speaker = "Lindsay", Text = "I call it hot ham water" },
        new Quote { QuoteId = 180, Speaker = "Unknown", Text = "He's a regular Freddie Wilson, that one" },
        new Quote { QuoteId = 181, Speaker = "Michael", Text = "Don't call it that" },
        new Quote { QuoteId = 182, Speaker = "Unknown", Text = "If you didn't have adult onset diabetes, I wouldn't mind giving you a little sugar" },
        new Quote { QuoteId = 183, Speaker = "GOB", Text = "You don't want a hungry dove down your pants" },
        new Quote { QuoteId = 184, Speaker = "GOB", Text = "That's how Tony Wonder lost a nut" },
        new Quote { QuoteId = 185, Speaker = "GOB", Text = "Why go to a banana stand when we can make YOUR banana stand?" },
        new Quote { QuoteId = 186, Speaker = "GOB", Text = "Don't worry, these young beauties have been nowhere near the bananas" },
        new Quote { QuoteId = 187, Speaker = "GeorgeSenior", Text = "And that's why you don't try to teach lessons to your father" },
        new Quote { QuoteId = 188, Speaker = "Unknown", Text = "We'll be the laughing stock of the boardwalk" },
        new Quote { QuoteId = 189, Speaker = "GOB", Text = "If you feel something moving down there, it's just the bird" },
        new Quote { QuoteId = 190, Speaker = "Unknown", Text = "I might have you beaten with a pillowcase full of batteries" },
        new Quote { QuoteId = 191, Speaker = "Tobias", Text = "The guy runs a prison; he can have any piece of ass he wants" },
        new Quote { QuoteId = 192, Speaker = "Michael", Text = "Who's the \"her\" in that sentence?" },
        new Quote { QuoteId = 193, Speaker = "Michael", Text = "Please don't call yourself that" },
        new Quote { QuoteId = 194, Speaker = "Unknown", Text = "I don't know why I always assume that everyone has read my screenplay" },
        new Quote { QuoteId = 195, Speaker = "GOB", Text = "I'm not going to spend this kind of money and not watch" },
        new Quote { QuoteId = 196, Speaker = "GOB", Text = "He showers her with club sauce" },
        new Quote { QuoteId = 197, Speaker = "Michael", Text = "You've never told me how many houses there are in the British Parliament" },
        new Quote { QuoteId = 198, Speaker = "Unknown", Text = "I think we could be more than just gym buddies" },
        new Quote { QuoteId = 199, Speaker = "Tobias", Text = "You're blowing my mind, Frank" },
        new Quote { QuoteId = 200, Speaker = "Unknown", Text = "The whole backside has moles" },
        new Quote { QuoteId = 201, Speaker = "Tobias", Text = "There's no \"I\" in \"win\"" },
        new Quote { QuoteId = 202, Speaker = "Tobias", Text = "Within her lies a queen" },
        new Quote { QuoteId = 203, Speaker = "Unknown", Text = "You can control your bladder when you're dead" },
        new Quote { QuoteId = 204, Speaker = "Tobias", Text = "I ought to pull down your pants and spank your ass raw" },
        new Quote { QuoteId = 205, Speaker = "Unknown", Text = "Why should you go to jail for a crime someone else noticed?" },
        new Quote { QuoteId = 206, Speaker = "Tobias", Text = "I was a professional twice over: an analyst and a therapist" },
        new Quote { QuoteId = 207, Speaker = "Tobias", Text = "The world's first analrapist" },
        new Quote { QuoteId = 208, Speaker = "Michael", Text = "I shall drop you off alive, hooker or no" },
        new Quote { QuoteId = 209, Speaker = "Unknown", Text = "They're polite and the men all sound gay, but they will rip out your heart" },
        new Quote { QuoteId = 210, Speaker = "Michael", Text = "I almost had Pop-Pop in Reno" },
        new Quote { QuoteId = 211, Speaker = "Tobias", Text = "If this tableau I recreate, perhaps I can re-snare my mate" },
        new Quote { QuoteId = 212, Speaker = "Unknown", Text = "I don't want anybody to go inside that musty claptrap" },
        new Quote { QuoteId = 213, Speaker = "GOB", Text = "We were both waiting for our dads at that garden where the little boy found the arm" },
        new Quote { QuoteId = 214, Speaker = "GOB", Text = "I kind of feel like that kid who found the severed hand" },
        new Quote { QuoteId = 215, Speaker = "GOB", Text = "I don't see you crying, robot" },
        new Quote { QuoteId = 216, Speaker = "Kitty", Text = "Say goodbye to these" },
        new Quote { QuoteId = 217, Speaker = "Unknown", Text = "I promised myself I wasn't going to become one of those people who were always going on about their screenplays" },
        new Quote { QuoteId = 218, Speaker = "Unknown", Text = "Nobody sells any coke in this pen without daddy getting a taste" },
        new Quote { QuoteId = 219, Speaker = "Oscar", Text = "You haven't seen a little box with a turtle on it, have you?" },
        new Quote { QuoteId = 220, Speaker = "Buster", Text = "My turtle was living in it before he ate all the grass and died" },
        new Quote { QuoteId = 221, Speaker = "Tobias", Text = "The scabs come right off" },
        new Quote { QuoteId = 222, Speaker = "Unknown", Text = "I can't say no to the woman who gave me chlamydia" },
        new Quote { QuoteId = 223, Speaker = "Tobias", Text = "People hear the name Tobias, they think big black guy" },
        new Quote { QuoteId = 224, Speaker = "GOB", Text = "I just don't want people's kids getting their sticky little fingers all over these $2,600 pants" },
        new Quote { QuoteId = 225, Speaker = "GOB", Text = "The guy who's dirty dancing with his niece is going to tell the guy in the $3,600 suit how to run the business. Come on" },
        new Quote { QuoteId = 226, Speaker = "Lucille", Text = "Suddenly playing with yourself is a scholarly pursuit" },
        new Quote { QuoteId = 227, Speaker = "Lucille", Text = "If I wanted something your thumb touched, I'd eat the inside of your ear" },
        new Quote { QuoteId = 228, Speaker = "Lucille", Text = "You let him go in the sun?" },
        new Quote { QuoteId = 229, Speaker = "Lucille", Text = "Then why don't you marry an ice cream sandwich?" },
        new Quote { QuoteId = 230, Speaker = "Buster", Text = "I will pack your sweet pink mouth with so much ice cream you'll be the envy of every Jerry and Jane on the block" },
        new Quote { QuoteId = 231, Speaker = "GeorgeSenior", Text = "I am having a love affair with this ice cream sandwich" },
        new Quote { QuoteId = 232, Speaker = "GeorgeSenior", Text = "Did you stick it to her?" },
        new Quote { QuoteId = 233, Speaker = "GeorgeSenior", Text = "Pop-Pop needs your hair" },
        new Quote { QuoteId = 234, Speaker = "Lucille", Text = "At least he's in prison, not an urn" },
        new Quote { QuoteId = 235, Speaker = "Unknown", Text = "You know the hair that no one's supposed to see?" },
        new Quote { QuoteId = 236, Speaker = "Unknown", Text = "Everyone put on white robes and outsmarted us" },
        new Quote { QuoteId = 237, Speaker = "Tobias", Text = "We shan't be telling your mother about this, shan't we?" },
        new Quote { QuoteId = 238, Speaker = "Unknown", Text = "Now there's somebody who needs a good mother" },
        new Quote { QuoteId = 239, Speaker = "Lucille", Text = "I'll leave when I'm good and ready" },
        new Quote { QuoteId = 240, Speaker = "Maeby", Text = "I need one of those necklaces in the shape of a T" },
        new Quote { QuoteId = 241, Speaker = "Unknown", Text = "There's a cream with real diamonds in it" },
        new Quote { QuoteId = 242, Speaker = "Tobias", Text = "You, sir, are a mouthful" },
        new Quote { QuoteId = 243, Speaker = "GOB", Text = "If I can't find a horny immigrant by then, I don't deserve to stay here" },
        new Quote { QuoteId = 244, Speaker = "Tobias", Text = "There's a man inside me, and only when he's finally out can I walk free of pain" },
        new Quote { QuoteId = 245, Speaker = "Tobias", Text = "I'm afraid I prematurely shot my wad on what was supposed to be a \"dry run\", if you will, so now I\'m afraid I have something of a mess on my hands" },
        new Quote { QuoteId = 246, Speaker = "GOB", Text = "I've made a huge mistake" },
        new Quote { QuoteId = 247, Speaker = "Tobias", Text = "You are playing adults with fully-formed libidos, not two young men playing grab-ass in the shower" },
        new Quote { QuoteId = 248, Speaker = "GeorgeMichael", Text = "I can't go on a million bike rides whenever you want me to" },
        new Quote { QuoteId = 249, Speaker = "GeorgeSenior", Text = "The doctor said there were claw marks on the walls of her uterus" },
        new Quote { QuoteId = 250, Speaker = "Buster", Text = "It's like she gets off on being withholding" },
        new Quote { QuoteId = 251, Speaker = "GOB", Text = "Look who's ragging on the old lady" },
        new Quote { QuoteId = 252, Speaker = "Lucille", Text = "Look at me, \"getting off\"" },
        new Quote { QuoteId = 253, Speaker = "Unknown", Text = "I always ended up on all fours" },
        new Quote { QuoteId = 254, Speaker = "Tobias", Text = "This kind of agility?" },
        new Quote { QuoteId = 255, Speaker = "Tobias", Text = "Do you see me more as the respected dramatic actor or more of the beloved comic actor?" },
        new Quote { QuoteId = 256, Speaker = "GOB", Text = "I don't even want to tell you what she wouldn't let me do to her in the car" },
        new Quote { QuoteId = 257, Speaker = "Buster", Text = "I thought you had class" },
        new Quote { QuoteId = 258, Speaker = "Tobias", Text = "Carl Weathers took everything from me" },
        new Quote { QuoteId = 259, Speaker = "Tobias", Text = "You could have been sleeping with Frightened Inmate #2" },
        new Quote { QuoteId = 260, Speaker = "GeorgeMichael", Text = "Some call me The Human Metronome" },
        new Quote { QuoteId = 261, Speaker = "GOB", Text = "So far it's been all chain and no ball" },
        new Quote { QuoteId = 262, Speaker = "Unknown", Text = "Not everything is strippers and booze and buckets of blood" },
        new Quote { QuoteId = 263, Speaker = "Unknown", Text = "You're out of the band" },
        new Quote { QuoteId = 264, Speaker = "Buster", Text = "I've already got a Lucille in my life" },
        new Quote { QuoteId = 265, Speaker = "Buster", Text = "Is this something society will allow?" },
        new Quote { QuoteId = 266, Speaker = "Buster", Text = "I just jumped through a plate glass window on a date" },
        new Quote { QuoteId = 267, Speaker = "Kitty", Text = "I have been Googling your father" },
        new Quote { QuoteId = 268, Speaker = "Unknown", Text = "I sold you for a pack of cigarettes" },
        new Quote { QuoteId = 269, Speaker = "GeorgeSenior", Text = "You don't fire crazy" },
        new Quote { QuoteId = 270, Speaker = "GeorgeSenior", Text = "All these books are cooked" },
        new Quote { QuoteId = 271, Speaker = "GeorgeMichael", Text = "It's like a mind puzzle, an awesome mind puzzle" },
        new Quote { QuoteId = 272, Speaker = "GeorgeMichael", Text = "Talk you off of what, Pop-Pop?" },
        new Quote { QuoteId = 273, Speaker = "GOB", Text = "Where once there was a yacht, now there is naught" },
        new Quote { QuoteId = 274, Speaker = "GOB", Text = "Who doesn't love the Jews?" },
        new Quote { QuoteId = 275, Speaker = "GeorgeMichael", Text = "I was going to smoke the marijuana like a cigarette" },
        new Quote { QuoteId = 276, Speaker = "Michael", Text = "They don't allow you to have bees in here" },
        new Quote { QuoteId = 277, Speaker = "Barry", Text = "I think something laid eggs on me" },
        new Quote { QuoteId = 278, Speaker = "Annyong", Text = "Mother say no carbohydrate for you if you ever going to get girlfriend that's not old lady" },
        new Quote { QuoteId = 279, Speaker = "Annyong", Text = "Maybe we should kiss again to teach them a lesson about obvious" },
        new Quote { QuoteId = 280, Speaker = "Lucille", Text = "Look how he zips now" },
        new Quote { QuoteId = 281, Speaker = "Unknown", Text = "I should have never taken the pumps out of here" },
        new Quote { QuoteId = 282, Speaker = "GOB", Text = "You just can't deal with the fact that I've got a super-thin wife with huge cans" },
        new Quote { QuoteId = 283, Speaker = "Unknown", Text = "Did you know that you can get a refill on any drink you want here, and it's free?" },
        new Quote { QuoteId = 284, Speaker = "Unknown", Text = "Aren't you the sweetest thing, spending some time with what's left of your uncle" },
        new Quote { QuoteId = 285, Speaker = "Unknown", Text = "He couldn't wait to swoop in and throw on the sailor suit" },
        new Quote { QuoteId = 286, Speaker = "Unknown", Text = "I got children all over town" },
        new Quote { QuoteId = 287, Speaker = "Buster", Text = "My father is my uncle" },
        new Quote { QuoteId = 288, Speaker = "Unknown", Text = "That's the kind of joke he would have loved" },
        new Quote { QuoteId = 289, Speaker = "Tobias", Text = "Who'd like a banger in the mouth?" },
        new Quote { QuoteId = 290, Speaker = "Michael", Text = "We just call it a sausage" },
        new Quote { QuoteId = 291, Speaker = "GOB", Text = "Franklin said some things Whitey just wasn't ready to hear" },
        new Quote { QuoteId = 292, Speaker = "Tobias", Text = "I forgot that we were in the colonies" },
        new Quote { QuoteId = 293, Speaker = "Unknown", Text = "Take me to your secular world" },
        new Quote { QuoteId = 294, Speaker = "GOB", Text = "My socks are wet" },
        new Quote { QuoteId = 295, Speaker = "GOB", Text = "Me quick, want slow" },
        new Quote { QuoteId = 296, Speaker = "Unknown", Text = "Tea for dong!" },
        new Quote { QuoteId = 297, Speaker = "Tobias", Text = "I'd want to get in there and find some answers" },
        new Quote { QuoteId = 298, Speaker = "Tobias", Text = "Excuse me for liking the way they shape my junk" },
        new Quote { QuoteId = 299, Speaker = "Ann", Text = "It's not just going to be my love and George Michael's, but God's love as well" },
        new Quote { QuoteId = 300, Speaker = "Unknown", Text = "Can it open a can?" },
        new Quote { QuoteId = 301, Speaker = "Unknown", Text = "A seal didn't bite your Linus off, right?" },
        new Quote { QuoteId = 302, Speaker = "Unknown", Text = "No, a seal didn't bite my Linus off" },
        new Quote { QuoteId = 303, Speaker = "GeorgeSenior", Text = "Up yours, granny!" },
        new Quote { QuoteId = 304, Speaker = "Lucille", Text = "You couldn't handle it!" },
        new Quote { QuoteId = 305, Speaker = "Tobias", Text = "Seems like only yesterday you were bursting forth from your mother's fertile womb" },
        new Quote { QuoteId = 306, Speaker = "Maeby", Text = "You don't see me nervous about being on my third Virgin Mary" },
        new Quote { QuoteId = 307, Speaker = "Lucille", Text = "You are a worse psychiatrist than you are a son-in-law, and you will never get work as an actor because you have no talent" },
        new Quote { QuoteId = 308, Speaker = "Tobias", Text = "I had no idea a ninety year-old man could cave in my chest cavity like that" },
        new Quote { QuoteId = 309, Speaker = "Tobias", Text = "I think your knee is on my heart" },
        new Quote { QuoteId = 310, Speaker = "Tobias", Text = "I'm afraid I prematurely shot my wad on what was supposed to be a dry run, if you will" },
        new Quote { QuoteId = 311, Speaker = "Lucille", Text = "I'm going to see if I can get a wrench to strip my nuts" },
        new Quote { QuoteId = 312, Speaker = "GeorgeSenior", Text = "I haven't had a massage since prison" },
        new Quote { QuoteId = 313, Speaker = "Lucille", Text = "He's an alpaca" },
        new Quote { QuoteId = 314, Speaker = "GOB", Text = "One of this guy's eyebrows just fell in the bowl of candy beans" },
        new Quote { QuoteId = 315, Speaker = "Michael", Text = "I think George Michael is hiding Ann in the attic" },
        new Quote { QuoteId = 316, Speaker = "Michael", Text = "It's as Ann as the nose on Plain's face" },
        new Quote { QuoteId = 317, Speaker = "GeorgeMichael", Text = "I have Pop-Pop in the attic" },
        new Quote { QuoteId = 318, Speaker = "Tobias", Text = "Who wants to go to the hospital?" },
        new Quote { QuoteId = 319, Speaker = "Tobias", Text = "That was 100% inappropriate, and I do apologize profusely" },
        new Quote { QuoteId = 320, Speaker = "Buster", Text = "I ought to point to Uncle Oscar's Charlie Browns next time you're on top of him, Mother" },
        new Quote { QuoteId = 321, Speaker = "Tobias", Text = "I figured if I blue myself early I'd be nice and relaxed for a 9:00 dinner reservation" },
        new Quote { QuoteId = 322, Speaker = "Lindsay", Text = "I can actually smear diamonds on my face, and it's only $400 a tub" },
        new Quote { QuoteId = 323, Speaker = "GeorgeMichael", Text = "She calls it a 'mayon-egg'" },
        new Quote { QuoteId = 324, Speaker = "Buster", Text = "Mom volunteered me for the Army just because the fat man dared her to" },
        new Quote { QuoteId = 325, Speaker = "GOB", Text = "The tears just aren't coming" },
        new Quote { QuoteId = 326, Speaker = "Unknown", Text = "You mean you can wear stripper clothes when you're not stripping?" },
        new Quote { QuoteId = 327, Speaker = "GeorgeSenior", Text = "You could hump that hood" },
        new Quote { QuoteId = 328, Speaker = "GeorgeMichael", Text = "What a fun sexy time for you" },
        new Quote { QuoteId = 329, Speaker = "Unknown", Text = "What I'm calling you is a television actor" },
        new Quote { QuoteId = 330, Speaker = "Unknown", Text = "There's only one man I've ever called a coward, and that's Brian Doyle Murray" },
        new Quote { QuoteId = 331, Speaker = "Unknown", Text = "We do not wag our genitals at one another to make a point" },
        new Quote { QuoteId = 332, Speaker = "GOB", Text = "It's a mainstay of the magician's toolkit, like how clowns always have a rag soaked in ether" },
        new Quote { QuoteId = 333, Speaker = "GOB", Text = "The worst that could happen is that I could spill coffee all over this $3,000 suit" },
        new Quote { QuoteId = 334, Speaker = "Unknown", Text = "I came out of you, he didn't" },
        new Quote { QuoteId = 335, Speaker = "Michael", Text = "I liked it better when he just said Annyong" },
        new Quote { QuoteId = 336, Speaker = "GeorgeSenior", Text = "Maybe it was the eleven months he spent in the womb" },
        new Quote { QuoteId = 337, Speaker = "Tobias", Text = "You dont cry when you take those off?" },
        new Quote { QuoteId = 338, Speaker = "GeorgeSenior", Text = "How many times I gotta tell this kid chicken wings?" },
        new Quote { QuoteId = 339, Speaker = "Tobias", Text = "Somebody is a rude Gus" },
        new Quote { QuoteId = 340, Speaker = "GOB", Text = "I can't even fake the death of a stripper" },
        new Quote { QuoteId = 341, Speaker = "GOB", Text = "You didn't eat that dove, did you?" },
        new Quote { QuoteId = 342, Speaker = "Unknown", Text = "If someone had left a note, this innocent man would still have his arm" },
        new Quote { QuoteId = 343, Speaker = "Unknown", Text = "You'd think a man locked up in prison would able to abstain" },
        new Quote { QuoteId = 344, Speaker = "Lucille", Text = "Your father with his disgusting tweaking" },
        new Quote { QuoteId = 345, Speaker = "Lucille", Text = "I couldn't breast feed any of you kids because of that man" },
        new Quote { QuoteId = 346, Speaker = "Michael", Text = "This is the nicest she's been since she found out that Rosa could breast-feed Buster" },
        new Quote { QuoteId = 347, Speaker = "GOB", Text = "First you dump all over it, now you want to know how it's done" },
        new Quote { QuoteId = 348, Speaker = "Tobias", Text = "I feel like the prettiest girl at the dance" },
        new Quote { QuoteId = 349, Speaker = "Tobias", Text = "I need to go take down the buffet and set up the leather pony" },
        new Quote { QuoteId = 350, Speaker = "GeorgeSenior", Text = "They cannot arrest a husband and wife for the same crime" },
        new Quote { QuoteId = 351, Speaker = "GeorgeMichael", Text = "Say what you want about America - thirteen bucks can still get you a hell of a lot of mice" },
        new Quote { QuoteId = 352, Speaker = "GOB", Text = "Who said anything bad about America?" },
        new Quote { QuoteId = 353, Speaker = "GeorgeMichael", Text = "So I'm thinking of getting a motorcycle" },
        new Quote { QuoteId = 354, Speaker = "Maeby", Text = "Your legs look exactly like mine, and I just shaved mine" },
        new Quote { QuoteId = 355, Speaker = "Tobias", Text = "I'm looking for something that says \"Dad likes leather\"" },
        new Quote { QuoteId = 356, Speaker = "Tobias", Text = "You have to be some sort of she-hulk to get this" },
        new Quote { QuoteId = 357, Speaker = "Buster", Text = "Mom, you're ruining our fort" },
        new Quote { QuoteId = 358, Speaker = "Unknown", Text = "Who'd want to mess with any of us?" },
        new Quote { QuoteId = 359, Speaker = "GeorgeMichael", Text = "Trying to introduce some edge to the whole palette" },
        new Quote { QuoteId = 360, Speaker = "Lucille", Text = "Is she the one who's going to take him to the dentist?" },
        new Quote { QuoteId = 361, Speaker = "UncleJack", Text = "You're right inside me now" },
        new Quote { QuoteId = 362, Speaker = "Unknown", Text = "I can't believe they wouldn't even give me a wheelchair ride" },
        new Quote { QuoteId = 363, Speaker = "Buster", Text = "Doesn't this make you want to have an ice-cream cone?" },
        new Quote { QuoteId = 364, Speaker = "Buster", Text = "I do believe there was some mention of some ice cream" },
        new Quote { QuoteId = 365, Speaker = "Buster", Text = "Does anyone know how to eat one of these?" },
        new Quote { QuoteId = 366, Speaker = "Tobias", Text = "There's a new daddy in town. A discipline daddy." },
        new Quote { QuoteId = 367, Speaker = "Unknown", Text = "I tried hitchhiking, but it's hard to do without a thumb" },
        new Quote { QuoteId = 368, Speaker = "Tobias", Text = "Now what we do is we paint our lips Joan Crawford red, pop on a little blue eyeliner and then plant a lipstick kiss on every one of them" },
        new Quote { QuoteId = 369, Speaker = "GOB", Text = "Still, where'd the lighter fluid come from?" },
        new Quote { QuoteId = 370, Speaker = "Unknown", Text = "Larry, go to a mirror" },
        new Quote { QuoteId = 371, Speaker = "Tobias", Text = "Why am I not going under water?" },
        new Quote { QuoteId = 372, Speaker = "Unknown", Text = "Why did I lose all the weight if they're going to put me in a pool cover?" },
        new Quote { QuoteId = 373, Speaker = "GeorgeMichael", Text = "I wish I could draw her nose" },
        new Quote { QuoteId = 374, Speaker = "Tobias", Text = "I just found out that my cellular telephone was a lemon" },
        new Quote { QuoteId = 375, Speaker = "Michael", Text = "Are you wearing my dead wife's maternity clothes?" },
        new Quote { QuoteId = 376, Speaker = "Unknown", Text = "I can't get this ham open" },
        new Quote { QuoteId = 377, Speaker = "Tobias", Text = "If he's got a shot with her, just give me a little tap on the fanny" },
        new Quote { QuoteId = 378, Speaker = "GOB", Text = "Now, when you do this without getting punched in the chest, you'll have more fun" },
        new Quote { QuoteId = 379, Speaker = "Tobias", Text = "The Blue Man Group might need me, and I do deserve a fancy phone" },
        new Quote { QuoteId = 380, Speaker = "Lucille", Text = "The doctor said I couldn't be a mother now if I tried" },
        new Quote { QuoteId = 381, Speaker = "Lindsay", Text = "I'm much, much, much older than 15" },
        new Quote { QuoteId = 382, Speaker = "Unknown", Text = "And the worst part is he thinks he's passing" },
        new Quote { QuoteId = 383, Speaker = "Unknown", Text = "Wow, that does sound like a little girl" },
        new Quote { QuoteId = 384, Speaker = "Barry", Text = "I'm going for a hot Ding Dong" },
        new Quote { QuoteId = 385, Speaker = "Lindsay", Text = "She said “tingling” like 75 times" },
        new Quote { QuoteId = 386, Speaker = "Lucille", Text = "You smell like a pine cone" },
        new Quote { QuoteId = 387, Speaker = "Unknown", Text = "I'm on bad mushrooms" },
        new Quote { QuoteId = 388, Speaker = "Barry", Text = "This close, they always look like landscape" },
        new Quote { QuoteId = 389, Speaker = "Unknown", Text = "There were cutoffs up here?" },
        new Quote { QuoteId = 390, Speaker = "Lucille", Text = "What are you doing with Mother's rape horn?" },
        new Quote { QuoteId = 391, Speaker = "Michael", Text = "Do you want to steer, or are you too old to sit on your pop's lap and drive?" },
        new Quote { QuoteId = 392, Speaker = "Unknown", Text = "They impounded my humble trailer" },
        new Quote { QuoteId = 393, Speaker = "Barry", Text = "Does this look contagious to you?" },
        new Quote { QuoteId = 394, Speaker = "Tobias", Text = "Nice to be back in a queen" },
        new Quote { QuoteId = 395, Speaker = "Tobias", Text = "Let the great experiment begin" },
        new Quote { QuoteId = 396, Speaker = "Michael", Text = "There's got to be a better way to say that" },
        new Quote { QuoteId = 397, Speaker = "GeorgeSenior", Text = "I am having the time of my life" },
        new Quote { QuoteId = 398, Speaker = "Michael", Text = "I haven't met Ann" },
        new Quote { QuoteId = 399, Speaker = "GeorgeMichael", Text = "I kind of want to buy her a diamond" },
        new Quote { QuoteId = 400, Speaker = "Michael", Text = "I'm sure that Egg is a very nice person" },
        new Quote { QuoteId = 401, Speaker = "Buster", Text = "I heard zoo noises" },
        new Quote { QuoteId = 402, Speaker = "Unknown", Text = "Which pinky do you use less?" },
        new Quote { QuoteId = 403, Speaker = "GOB", Text = "Nothing on the inside" },
        new Quote { QuoteId = 404, Speaker = "Lindsay", Text = "I'm not proud of the way I was so grossed out when I found out you were gross before" },
        new Quote { QuoteId = 405, Speaker = "Buster", Text = "I'm just hoping to get mildly injured so I can get out of the Army" },
        new Quote { QuoteId = 406, Speaker = "Unknown", Text = "I think my nipples are bleeding" },
        new Quote { QuoteId = 407, Speaker = "Unknown", Text = "Flashes of Quincy" },
        new Quote { QuoteId = 408, Speaker = "Unknown", Text = "I think the plant lady's wearing a thong" },
        new Quote { QuoteId = 409, Speaker = "Unknown", Text = "Don't be such an Ann hog" },
        new Quote { QuoteId = 410, Speaker = "Unknown", Text = "Go see a Star War" },
        new Quote { QuoteId = 411, Speaker = "Unknown", Text = "Why am I not blacking out?" },
        new Quote { QuoteId = 412, Speaker = "Unknown", Text = "He swore by that Glisten" },
        new Quote { QuoteId = 413, Speaker = "Unknown", Text = "Let's go dig up your uncle" },
        new Quote { QuoteId = 414, Speaker = "Unknown", Text = "I will be head to toe in blue makeup until 8:01 in case the Blue Man Group needs their understudy" },
        new Quote { QuoteId = 415, Speaker = "Unknown", Text = "Are we having yams?" },
        new Quote { QuoteId = 416, Speaker = "Unknown", Text = "First I blow him, then I poke him" },
        new Quote { QuoteId = 417, Speaker = "Unknown", Text = "I don't think we need people trying to compete with what I'm wearing" },
        new Quote { QuoteId = 418, Speaker = "Unknown", Text = "Don't ask me, I'm just the boy's father" },
        new Quote { QuoteId = 419, Speaker = "Unknown", Text = "No one would believe that a woman like me would have a gay son" },
        new Quote { QuoteId = 420, Speaker = "Unknown", Text = "I can see marinating a chicken in that" },
        new Quote { QuoteId = 421, Speaker = "Unknown", Text = "Your Tweety Bird dance just cost us a run, you moron" },
        new Quote { QuoteId = 422, Speaker = "Unknown", Text = "How do we filter out the teases? We don't let them in." },
        new Quote { QuoteId = 423, Speaker = "Unknown", Text = "I am stable as a table" },
        new Quote { QuoteId = 424, Speaker = "Unknown", Text = "I would hardly call my mother a girl, but yes, she's still very much a part of my life" },
        new Quote { QuoteId = 425, Speaker = "Unknown", Text = "Everybody thinks they're Frank Sinatra" },
        new Quote { QuoteId = 426, Speaker = "Unknown", Text = "They make me feel dressier" },
        new Quote { QuoteId = 427, Speaker = "Unknown", Text = "A piano could stand on those legs" },
        new Quote { QuoteId = 428, Speaker = "Unknown", Text = "Guess she didn't see the drawings" },
        new Quote { QuoteId = 429, Speaker = "Unknown", Text = "You have undone all of Dr. Sandor Plumb's work" },
        new Quote { QuoteId = 430, Speaker = "Unknown", Text = "I need to prove to her that I'm not just a man, but a man's man" },
        new Quote { QuoteId = 431, Speaker = "Unknown", Text = "Shall I put the Posturepedic in the down position?" },
        new Quote { QuoteId = 432, Speaker = "Unknown", Text = "Read me the appetizers again" },
        new Quote { QuoteId = 433, Speaker = "Unknown", Text = "Did you have too much club sauce on your calamari?" },
        new Quote { QuoteId = 434, Speaker = "Unknown", Text = "I tried to drink some of the water, and it was too hot and it tasted like soy sauce" },
        new Quote { QuoteId = 435, Speaker = "Unknown", Text = "I think the teriyaki chicken burst" },
        new Quote { QuoteId = 436, Speaker = "Unknown", Text = "This isn't turning into the party hangout I hoped" },
        new Quote { QuoteId = 437, Speaker = "Unknown", Text = "Stick a wrench in me, I'm done" },
        new Quote { QuoteId = 438, Speaker = "Unknown", Text = "Someone order 140 pounds of upper-body strength?" },
        new Quote { QuoteId = 439, Speaker = "Unknown", Text = "It's just something the body does when you shake it" },
        new Quote { QuoteId = 440, Speaker = "Unknown", Text = "Well, I'm all grown up now" },
        new Quote { QuoteId = 441, Speaker = "Unknown", Text = "How'd you like to take a nap, baldy?" },
        new Quote { QuoteId = 442, Speaker = "Unknown", Text = "Let's not spin in the comfy chair" },
        new Quote { QuoteId = 443, Speaker = "Unknown", Text = "I got Michael out of his marriage, didn't I?" },
        new Quote { QuoteId = 444, Speaker = "Unknown", Text = "I need macaroons" },
        new Quote { QuoteId = 445, Speaker = "Unknown", Text = "You can win every argument like that, but that does not make you right" },
        new Quote { QuoteId = 446, Speaker = "Unknown", Text = "I really hate it when you put on the God costume" },
        new Quote { QuoteId = 447, Speaker = "Unknown", Text = "I'm cloaking myself in her scent" },
        new Quote { QuoteId = 448, Speaker = "Unknown", Text = "I was made to understand that there would be grilled cheese sandwiches here" },
        new Quote { QuoteId = 449, Speaker = "Unknown", Text = "Will someone please have the decency to punch me in the face?" },
        new Quote { QuoteId = 450, Speaker = "Unknown", Text = "Mom always taught us to curl up in a ball and remain motionless when confronted" },
        new Quote { QuoteId = 451, Speaker = "Buster", Text = "We have unlimited juice?" },
        new Quote { QuoteId = 452, Speaker = "Buster", Text = "You old horny slut" },
        new Quote { QuoteId = 453, Speaker = "Unknown", Text = "We all know you're Annyong" },
        new Quote { QuoteId = 454, Speaker = "Buster", Text = "No, Mother, I can blow myself" },
        new Quote { QuoteId = 455, Speaker = "Michael", Text = "Her?" },
        new Quote { QuoteId = 456, Speaker = "Unknown", Text = "She was made in a cup, like soup" },
        new Quote { QuoteId = 457, Speaker = "Tobias", Text = "Oh, I'm sorry, I forgot: your wife is dead" },
        new Quote { QuoteId = 458, Speaker = "Unknown", Text = "The one thing I will never do is not tell him that I'm taking him to a cabin in the woods and then not take him" },
        new Quote { QuoteId = 459, Speaker = "GeorgeSenior", Text = "He was our miracle baby" },
        new Quote { QuoteId = 460, Speaker = "GOB", Text = "It's like my heart is getting hard" },
        new Quote { QuoteId = 461, Speaker = "GOB", Text = "I know what an erection feels like, Michael" },
        new Quote { QuoteId = 462, Speaker = "Unknown", Text = "Those aren't even birds" },
        new Quote { QuoteId = 463, Speaker = "GOB", Text = "But I'm white" },
        new Quote { QuoteId = 464, Speaker = "GOB", Text = "It ain't easy being white" },
        new Quote { QuoteId = 465, Speaker = "Buster", Text = "I'm Mom and I want to shoot down everything you say so I feel good about myself" },
        new Quote { QuoteId = 466, Speaker = "Unknown", Text = "Lets deal some drugs" },
        new Quote { QuoteId = 467, Speaker = "Unknown", Text = "Why do you think I wear these?" },
        new Quote { QuoteId = 468, Speaker = "GOB", Text = "A magician never reveals his secrets" },
        new Quote { QuoteId = 469, Speaker = "Unknown", Text = "When's that voice gonna drop?" },
        new Quote { QuoteId = 470, Speaker = "Maeby", Text = "I'm gonna go get sexy" },
        new Quote { QuoteId = 471, Speaker = "Lucille", Text = "They said he was some kind of scientist" },
        new Quote { QuoteId = 472, Speaker = "Michael", Text = "Speaking of settling, How's Ann?" },
        new Quote { QuoteId = 473, Speaker = "GeorgeSenior", Text = "It's hard to gauge time" },
        new Quote { QuoteId = 474, Speaker = "GeorgeMichael", Text = "I like the way they think" },
        new Quote { QuoteId = 475, Speaker = "GeorgeMichael", Text = "I was hoping he would be gifted sexually" },
        new Quote { QuoteId = 476, Speaker = "Tobias", Text = "If this were a Lifetime Moment of Truth movie, this would be our act break" },
        new Quote { QuoteId = 477, Speaker = "Unknown", Text = "A flower in my garden, a mystery in my panties" },
        new Quote { QuoteId = 478, Speaker = "Buster", Text = "I'm a scholar. I enjoy scholarly pursuits" },
        new Quote { QuoteId = 479, Speaker = "Unknown", Text = "The warden could easily be black" },
        new Quote { QuoteId = 480, Speaker = "Tobias", Text = "Who is this shiny building of a man?" },
        new Quote { QuoteId = 481, Speaker = "Buster", Text = "Chickens don't clap" },
        new Quote { QuoteId = 482, Speaker = "Unknown", Text = "I've got a stair car full of Mexican laborers that would love a day's work" },
        new Quote { QuoteId = 483, Speaker = "Unknown", Text = "Are beads cheap?" },
        new Quote { QuoteId = 484, Speaker = "Unknown", Text = "We'll see who brings in more honey" },
        new Quote { QuoteId = 485, Speaker = "Michael", Text = "He's thinking about bees again" },
        new Quote { QuoteId = 486, Speaker = "Unknown", Text = "We're going to have to figure out something to do so that people can look at you without wanting to kill themselves" },
        new Quote { QuoteId = 487, Speaker = "GOB", Text = "You don’t know a good bird hospital, do you?" },
        new Quote { QuoteId = 488, Speaker = "GOB", Text = "Hair up, glasses off" }
      );
    }
  }
}