using Microsoft.EntityFrameworkCore;

namespace ArrestedDevelopmentApi.Models
{
  public class ArrestedDevelopmentApiContext : DbContext
  {
    public DbSet<Quote> Quotes { get; set; }

    public ArrestedDevelopmentApiContext(DbContextOptions<ArrestedDevelopmentApiContext> options) : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder builder)
    {
      builder.Entity<Quote>().HasData(
        new Quote { QuoteId = 1, Speaker = "GOB", Text = "Hair up, glasses off", NumberOfWords = 4 },
        new Quote { QuoteId = 2, Speaker = "Unknown", Text = "You boys know how to shovel coal?", NumberOfWords = 7 },
        new Quote { QuoteId = 3, Speaker = "Buster", Text = "What do you expect, Mother? I'm half machine!", NumberOfWords = 8 },
        new Quote { QuoteId = 4, Speaker = "Buster", Text = "I'm a monster!", NumberOfWords = 3 },
        new Quote { QuoteId = 5, Speaker = "Unknown", Text = "It's a good thing he's already got that little scooter", NumberOfWords = 10 },
        new Quote { QuoteId = 6, Speaker = "Unknown", Text = "A heart attack never stopped old Big Bear", NumberOfWords = 8 },
        new Quote { QuoteId = 7, Speaker = "Buster", Text = "I didn't even know we were calling him Big Bear", NumberOfWords = 10 },
        new Quote { QuoteId = 8, Speaker = "Unknown", Text = "You could charm the black off a telegram boy", NumberOfWords = 9 },
        new Quote { QuoteId = 9, Speaker = "GOB", Text = "Did you see the new Poof?", NumberOfWords = 6 },
        new Quote { QuoteId = 10, Speaker = "Lucille", Text = "I love all of my children equally", NumberOfWords = 7 },
        new Quote { QuoteId = 11, Speaker = "Lucille", Text = "No one's called him Baby Buster since high school", NumberOfWords = 9 },
        new Quote { QuoteId = 12, Speaker = "Unknown", Text = "They didn't sneak into this country to be your friends", NumberOfWords = 10 },
        new Quote { QuoteId = 13, Speaker = "Unknown", Text = "You were just a turd out there, you know?", NumberOfWords = 9 },
        new Quote { QuoteId = 14, Speaker = "Buster", Text = "This party is going to be off the hook", NumberOfWords = 9 },
        new Quote { QuoteId = 15, Speaker = "Unknown", Text = "I hear the jury's still out on science", NumberOfWords = 8 },
        new Quote { QuoteId = 16, Speaker = "Buster", Text = "Like anyone would want to \"R\" her", NumberOfWords = 7 },
        new Quote { QuoteId = 17, Speaker = "Buster", Text = "Can't a guy call his mother pretty without it seeming strange?", NumberOfWords = 11 },
        new Quote { QuoteId = 18, Speaker = "Buster", Text = "This is the best free scrapbooking class I've ever taken", NumberOfWords = 10 },
        new Quote { QuoteId = 19, Speaker = "Unknown", Text = "Go ahead, touch the Cornballer", NumberOfWords = 5 },
        new Quote { QuoteId = 20, Speaker = "Buster", Text = "I'm going to run this through again on \"pots and pans\"", NumberOfWords = 11 },
        new Quote { QuoteId = 21, Speaker = "Unknown", Text = "I've been in the film business for a while but I just can't seem to get one in the can", NumberOfWords = 20 },
        new Quote { QuoteId = 22, Speaker = "Tobias", Text = "I will be a bigger and hairier mole than the one on your inner left thigh", NumberOfWords = 16 },
        new Quote { QuoteId = 23, Speaker = "Lucille", Text = "I want to cry so bad, but I don't think I can spare the moisture", NumberOfWords = 15 },
        new Quote { QuoteId = 24, Speaker = "GeorgeMichael", Text = "Maybe it was the other George Michael", NumberOfWords = 7 },
        new Quote { QuoteId = 25, Speaker = "Unknown", Text = "I'm tired of trying to find happiness through lies and self-medicating", NumberOfWords = 11 },
        new Quote { QuoteId = 26, Speaker = "Buster", Text = "It's so watery, and yet there's a smack of ham to it", NumberOfWords = 12 },
        new Quote { QuoteId = 27, Speaker = "Buster", Text = "The seal is for marksmanship, and the gorilla is for sand racing", NumberOfWords = 12 },
        new Quote { QuoteId = 28, Speaker = "Michael", Text = "After all these years, God's not going to take a call from you", NumberOfWords = 13 },
        new Quote { QuoteId = 29, Speaker = "GOB", Text = "You mean the guy we're meeting with can't even grow his own hair?", NumberOfWords = 13 },
        new Quote { QuoteId = 30, Speaker = "Tobias", Text = "I thought the two of us could talk man-on-man", NumberOfWords = 9 },
        new Quote { QuoteId = 31, Speaker = "Tobias", Text = "I spent so much time making sweet love on my wife that it's hard to hear anything over the clatter of her breasts", NumberOfWords = 23 },
        new Quote { QuoteId = 32, Speaker = "Unknown", Text = "You've been warned about touching", NumberOfWords = 5 },
        new Quote { QuoteId = 33, Speaker = "Unknown", Text = "No touching", NumberOfWords = 2 },
        new Quote { QuoteId = 34, Speaker = "Unknown", Text = "I think I maced a crane", NumberOfWords = 6 },
        new Quote { QuoteId = 35, Speaker = "Lindsay", Text = "Wine only turns to alcohol if you let it sit", NumberOfWords = 10 },
        new Quote { QuoteId = 36, Speaker = "Tobias", Text = "I see you've wasted no time in filling my seat hole", NumberOfWords = 11 },
        new Quote { QuoteId = 37, Speaker = "GOB", Text = "I'm going to buy you the single healthiest call girl this town has ever seen", NumberOfWords = 15 },
        new Quote { QuoteId = 38, Speaker = "GOB", Text = "Turn this skiff around", NumberOfWords = 4 },
        new Quote { QuoteId = 39, Speaker = "Buster", Text = "I never thought I'd miss a hand so much", NumberOfWords = 9 },
        new Quote { QuoteId = 40, Speaker = "Tobias", Text = "I can just taste those meaty leading man parts in my mouth.", NumberOfWords = 12 },
        new Quote { QuoteId = 41, Speaker = "Lucille", Text = "Everyone's laughing and riding and cornholing except Buster", NumberOfWords = 8 },
        new Quote { QuoteId = 42, Speaker = "Unknown", Text = "You can always tell a Milford man", NumberOfWords = 7 },
        new Quote { QuoteId = 43, Speaker = "Tobias", Text = "Let me take off my assistant's skirt and put on my Barbra-Streisand-in-The-Prince-of-Tides ass-masking therapist pantsuit", NumberOfWords = 15 },
        new Quote { QuoteId = 45, Speaker = "Tobias", Text = "Don't leave your Uncle T-Bag hanging", NumberOfWords = 6 },
        new Quote { QuoteId = 46, Speaker = "Michael", Text = "What have we always said is the most important thing?", NumberOfWords = 10 },
        new Quote { QuoteId = 47, Speaker = "Buster", Text = "We're just blowing through nap time, aren't we?", NumberOfWords = 8 },
        new Quote { QuoteId = 48, Speaker = "Franklin", Text = "Let me give that oatmeal some brown sugar", NumberOfWords = 8 },
        new Quote { QuoteId = 49, Speaker = "Lucille", Text = "A sea of waiters and no one will take a drink order", NumberOfWords = 12 },
        new Quote { QuoteId = 50, Speaker = "Barry", Text = "Those are balls", NumberOfWords = 3 },
        new Quote { QuoteId = 51, Speaker = "Tobias", Text = "I'm gonna build me an airport, put my name on it", NumberOfWords = 11 },
        new Quote { QuoteId = 52, Speaker = "Tobias", Text = "Let me out that queen", NumberOfWords = 5 },
        new Quote { QuoteId = 53, Speaker = "Tobias", Text = "Do these effectively hide my thunder?", NumberOfWords = 6 },
        new Quote { QuoteId = 54, Speaker = "Buster", Text = "You just grab that brownish area by its points and you don't let go no matter what your mother tells you", NumberOfWords = 21 },
        new Quote { QuoteId = 55, Speaker = "Tobias", Text = "I guess you can say I'm buy-curious", NumberOfWords = 7 },
        new Quote { QuoteId = 56, Speaker = "Unknown", Text = "The soup of the day is bread", NumberOfWords = 7 },
        new Quote { QuoteId = 57, Speaker = "GeorgeMichael", Text = "I could use a leather jacket for when I'm on my hog and have to go into a controlled slide", NumberOfWords = 20 },
        new Quote { QuoteId = 58, Speaker = "Buster", Text = "Are you at all concerned about an uprising?", NumberOfWords = 8 },
        new Quote { QuoteId = 59, Speaker = "Tobias", Text = "In the dark, it all looks the same", NumberOfWords = 8 },
        new Quote { QuoteId = 60, Speaker = "Tobias", Text = "Look at us, crying like a bunch of girls on the last day of camp", NumberOfWords = 15 },
        new Quote { QuoteId = 61, Speaker = "GeorgeSenior", Text = "You just made a fool out of yourself in front of T-Bone", NumberOfWords = 12 },
        new Quote { QuoteId = 62, Speaker = "GOB", Text = "I hope you also carry a spare bowl of candy beans", NumberOfWords = 11 },
        new Quote { QuoteId = 63, Speaker = "Michael", Text = "You can't just comb that out and reset it?", NumberOfWords = 9 },
        new Quote { QuoteId = 64, Speaker = "Lucille", Text = "Look what the homosexuals have done to me", NumberOfWords = 8 },
        new Quote { QuoteId = 65, Speaker = "Lucille", Text = "Everything they do is so dramatic and flamboyant, it just makes me want to set myself on fire", NumberOfWords = 18 },
        new Quote { QuoteId = 66, Speaker = "GeorgeSenior", Text = "I may have committed some light treason", NumberOfWords = 7 },
        new Quote { QuoteId = 67, Speaker = "Lucille", Text = "I don't understand the question and I won't respond to it", NumberOfWords = 11 },
        new Quote { QuoteId = 68, Speaker = "GeorgeSenior", Text = "There's always money in the banana stand", NumberOfWords = 7 },
        new Quote { QuoteId = 69, Speaker = "Tobias", Text = "In this business of show, you have to have the heart of an angel and the hyde of an elephant", NumberOfWords = 20 },
        new Quote { QuoteId = 70, Speaker = "GeorgeSenior", Text = "Too many lives have been ruined because some cheap waitress at a HoJo said she used an I.U.D.", NumberOfWords = 18 },
        new Quote { QuoteId = 71, Speaker = "Buster", Text = "Do you think I could have a hit of that juice box?", NumberOfWords = 12 },
        new Quote { QuoteId = 72, Speaker = "Lucille", Text = "Suddenly he's too much of a big shot to brush Mother's hair", NumberOfWords = 12 },
        new Quote { QuoteId = 73, Speaker = "Buster", Text = "It walked on my pillow", NumberOfWords = 5 },
        new Quote { QuoteId = 74, Speaker = "Michael", Text = "That's not a spinner", NumberOfWords = 4 },
        new Quote { QuoteId = 75, Speaker = "Buster", Text = "I thought I saw a graham cracker out there", NumberOfWords = 9 },
        new Quote { QuoteId = 76, Speaker = "CarlWeathers", Text = "There's still plenty of meat on that bone", NumberOfWords = 8 },
        new Quote { QuoteId = 77, Speaker = "CarlWeathers", Text = "Now you take this home, throw it in a pot, add some broth, a potato", NumberOfWords = 15 },
        new Quote { QuoteId = 78, Speaker = "CarlWeathers", Text = "Baby, you got a stew going", NumberOfWords = 21 },
        new Quote { QuoteId = 79, Speaker = "CarlWeathers", Text = "Never once touched my per diem", NumberOfWords = 6 },
        new Quote { QuoteId = 80, Speaker = "Buster", Text = "Army had a half day", NumberOfWords = 5 },
        new Quote { QuoteId = 81, Speaker = "Michael", Text = "The mere fact that you call making love \"pop pop\" tells me that you're not ready", NumberOfWords = 16 },
        new Quote { QuoteId = 82, Speaker = "Unknown", Text = "I'd have to get up pretty early in the morning to get drunk by 1 o' clock", NumberOfWords = 17 },
        new Quote { QuoteId = 83, Speaker = "Tobias", Text = "There are dozens of us", NumberOfWords = 5 },
        new Quote { QuoteId = 84, Speaker = "Michael", Text = "I think you're going to be surprised at some of your phrasing", NumberOfWords = 12 },
        new Quote { QuoteId = 85, Speaker = "GeorgeSenior", Text = "Stop licking my hand, you horse's ass", NumberOfWords = 7 },
        new Quote { QuoteId = 86, Speaker = "Tobias", Text = "I'm afraid I just blue myself", NumberOfWords = 6 },
        new Quote { QuoteId = 87, Speaker = "Lindsay", Text = "Why don't we just take an ad out in \"I'm Poor\" magazine?", NumberOfWords = 12 },
        new Quote { QuoteId = 88, Speaker = "Unknown", Text = "And that's why you always leave a note", NumberOfWords = 8 },
        new Quote { QuoteId = 89, Speaker = "Unknown", Text = "It's not your fault your parents were cousins, but here we are", NumberOfWords = 12 },
        new Quote { QuoteId = 90, Speaker = "Unknown", Text = "You're going to get some hop-ons", NumberOfWords = 6 },
        new Quote { QuoteId = 91, Speaker = "GOB", Text = "It just seems like there's still light coming in from under the door", NumberOfWords = 13 },
        new Quote { QuoteId = 92, Speaker = "Buster", Text = "I'm leaving my mother for you", NumberOfWords = 6 },
        new Quote { QuoteId = 93, Speaker = "Buster", Text = "You're replacing my mother", NumberOfWords = 4 },
        new Quote { QuoteId = 94, Speaker = "Tobias", Text = "Even if it means me taking a chubby, I will suck it up", NumberOfWords = 13 },
        new Quote { QuoteId = 95, Speaker = "Tobias", Text = "If she's not going to say anything, I certainly can't help her", NumberOfWords = 12 },
        new Quote { QuoteId = 96, Speaker = "Unknown", Text = "I hate this doctor", NumberOfWords = 4 },
        new Quote { QuoteId = 97, Speaker = "Unknown", Text = "That's like comparing apples and some fruit nobody's ever heard of", NumberOfWords = 11 },
        new Quote { QuoteId = 98, Speaker = "SteveHolt", Text = "Is that what's going to happen to my hair?", NumberOfWords = 9 },
        new Quote { QuoteId = 99, Speaker = "Unknown", Text = "Finally, some good news from this guy", NumberOfWords = 7 },
        new Quote { QuoteId = 100, Speaker = "Unknown", Text = "There's no other way to take that", NumberOfWords = 7 },
        new Quote { QuoteId = 101, Speaker = "Unknown", Text = "He's lost his left hand, so he's going to be all right", NumberOfWords = 12 },
        new Quote { QuoteId = 102, Speaker = "Tobias", Text = "Perhaps an attic shall I seek", NumberOfWords = 6 },
        new Quote { QuoteId = 104, Speaker = "Michael", Text = "He\'s definitely got a type", NumberOfWords = 5 },
        new Quote { QuoteId = 105, Speaker = "GOB", Text = "That's my son, you pothead", NumberOfWords = 5 },
        new Quote { QuoteId = 106, Speaker = "GOB", Text = "God knows they're squinters", NumberOfWords = 4 },
        new Quote { QuoteId = 107, Speaker = "Rita", Text = "Instead of making houses, maybe you should make land on the ocean", NumberOfWords = 12 },
        new Quote { QuoteId = 108, Speaker = "Rita", Text = "Maybe you're not smart either. I didn't know until they told me", NumberOfWords = 12 },
        new Quote { QuoteId = 109, Speaker = "Unknown", Text = "I've opened a door here that I regret", NumberOfWords = 8 },
        new Quote { QuoteId = 110, Speaker = "Unknown", Text = "What's Spanish for \"I know you speak English\"?", NumberOfWords = 8 },
        new Quote { QuoteId = 111, Speaker = "Unknown", Text = "You gave us cereal in an ashtray", NumberOfWords = 7 },
        new Quote { QuoteId = 112, Speaker = "Unknown", Text = "My name is Judge", NumberOfWords = 4 },
        new Quote { QuoteId = 113, Speaker = "Oscar", Text = "Why can't I have hair and money and him nothing?", NumberOfWords = 10 },
        new Quote { QuoteId = 114, Speaker = "Tobias", Text = "There's the woman I'm sexually attracted to", NumberOfWords = 7 },
        new Quote { QuoteId = 115, Speaker = "Buster", Text = "I was trained by Army", NumberOfWords = 5 },
        new Quote { QuoteId = 116, Speaker = "Tobias", Text = "I don't want to blame it all on 9/11, but it certainly didn't help", NumberOfWords = 14 },
        new Quote { QuoteId = 117, Speaker = "Annyong", Text = "Annyong", NumberOfWords = 1 },
        new Quote { QuoteId = 118, Speaker = "Unknown", Text = "Brand new cars don't get waxed", NumberOfWords = 6 },
        new Quote { QuoteId = 119, Speaker = "Unknown", Text = "Maybe I'll put it in her brownie", NumberOfWords = 7 },
        new Quote { QuoteId = 120, Speaker = "Tobias", Text = "You can sink your arrow into my buttocks any time", NumberOfWords = 10 },
        new Quote { QuoteId = 121, Speaker = "Unknown", Text = "I thought it was a pool toy", NumberOfWords = 7 },
        new Quote { QuoteId = 122, Speaker = "Tobias", Text = "I wouldn't mind kissing that man between the cheeks", NumberOfWords = 9 },
        new Quote { QuoteId = 123, Speaker = "GOB", Text = "Are those police boats?", NumberOfWords = 4 },
        new Quote { QuoteId = 125, Speaker = "GOB", Text = "Illusions, Michael", NumberOfWords = 2 },
        new Quote { QuoteId = 126, Speaker = "Buster", Text = "Clearly the blue part is the land", NumberOfWords = 7 },
        new Quote { QuoteId = 127, Speaker = "Michael", Text = "I don't know what I expected", NumberOfWords = 6 },
        new Quote { QuoteId = 128, Speaker = "Tobias", Text = "Huzzah!", NumberOfWords = 1 },
        new Quote { QuoteId = 129, Speaker = "Tobias", Text = "It's a wonderful restaurant", NumberOfWords = 4 },
        new Quote { QuoteId = 130, Speaker = "Michael", Text = "Why are you squeezing me with your body?", NumberOfWords = 8 },
        new Quote { QuoteId = 131, Speaker = "Unknown", Text = "He's going to be all right", NumberOfWords = 6 },
        new Quote { QuoteId = 132, Speaker = "Unknown", Text = "I was set up by the Brits", NumberOfWords = 7 },
        new Quote { QuoteId = 133, Speaker = "Lindsay", Text = "Say something that will terrify me", NumberOfWords = 6 },
        new Quote { QuoteId = 134, Speaker = "GOB", Text = "I'll buy you a hundred George Michaels that you can teach to drive", NumberOfWords = 13 },
        new Quote { QuoteId = 135, Speaker = "GOB", Text = "I should be in this Poof", NumberOfWords = 6 },
        new Quote { QuoteId = 136, Speaker = "TonyWonder", Text = "Did somebody say Wonder?", NumberOfWords = 4 },
        new Quote { QuoteId = 137, Speaker = "GOB", Text = "She turns illusions for money", NumberOfWords = 5 },
        new Quote { QuoteId = 138, Speaker = "Lucille", Text = "Everything I've said about you can be covered with makeup and a lie about a thyroid problem", NumberOfWords = 17 },
        new Quote { QuoteId = 139, Speaker = "Buster", Text = "He just wants to see boys' Linuses", NumberOfWords = 7 },
        new Quote { QuoteId = 140, Speaker = "Unknown", Text = "Half your testicle was hanging out of that thing", NumberOfWords = 9 },
        new Quote { QuoteId = 141, Speaker = "Unknown", Text = "Give me an old pro like a Robert Redford", NumberOfWords = 9 },
        new Quote { QuoteId = 142, Speaker = "Unknown", Text = "Give my son the juice", NumberOfWords = 5 },
        new Quote { QuoteId = 143, Speaker = "Unknown", Text = "You look like the window of a butcher shop", NumberOfWords = 9 },
        new Quote { QuoteId = 144, Speaker = "Unknown", Text = "You told me I wasn't fit to serve", NumberOfWords = 8 },
        new Quote { QuoteId = 145, Speaker = "Buster", Text = "They even touched my Charlie Browns", NumberOfWords = 6 },
        new Quote { QuoteId = 146, Speaker = "Buster", Text = "It's tired in here", NumberOfWords = 4 },
        new Quote { QuoteId = 147, Speaker = "Buster", Text = "Make love in your own hand, mother", NumberOfWords = 7 },
        new Quote { QuoteId = 148, Speaker = "Buster", Text = "Sometimes love should be terrifying", NumberOfWords = 5 },
        new Quote { QuoteId = 149, Speaker = "Buster", Text = "My Army training tells me that this is going to be a hot mission", NumberOfWords = 14 },
        new Quote { QuoteId = 152, Speaker = "Buster", Text = "Can't you keep my hand to yourself?", NumberOfWords = 7 },
        new Quote { QuoteId = 153, Speaker = "Buster", Text = "Have you seen my rubber hand?", NumberOfWords = 6 },
        new Quote { QuoteId = 154, Speaker = "Buster", Text = "I've always loved those leathery little snappy faces", NumberOfWords = 8 },
        new Quote { QuoteId = 155, Speaker = "GOB", Text = "Soft and alive", NumberOfWords = 3 },
        new Quote { QuoteId = 156, Speaker = "Unknown", Text = "It wasn't really the pronunciation that bothered me", NumberOfWords = 8 },
        new Quote { QuoteId = 157, Speaker = "Buster", Text = "My hook is stuck in the stair car", NumberOfWords = 8 },
        new Quote { QuoteId = 158, Speaker = "Unknown", Text = "And that's why you don't use one-armed persons to teach lessons", NumberOfWords = 11 },
        new Quote { QuoteId = 159, Speaker = "GOB", Text = "He's a robot!", NumberOfWords = 3 },
        new Quote { QuoteId = 160, Speaker = "Buster", Text = "If the only thing I could do was lay in bed all day and eat soup, I'd be happy", NumberOfWords = 19 },
        new Quote { QuoteId = 161, Speaker = "Buster", Text = "I could just take it through a tube", NumberOfWords = 8 },
        new Quote { QuoteId = 162, Speaker = "Unknown", Text = "Never let me die", NumberOfWords = 4 },
        new Quote { QuoteId = 163, Speaker = "Buster", Text = "When I miss your lips, I'll put a fig in my mouth", NumberOfWords = 12 },
        new Quote { QuoteId = 164, Speaker = "Buster", Text = "My love thinks I'm a coward just because I wasted precious hospital resources to avoid my legal obligation", NumberOfWords = 18 },
        new Quote { QuoteId = 165, Speaker = "Unknown", Text = "I've always pictured him in a lighthouse", NumberOfWords = 7 },
        new Quote { QuoteId = 166, Speaker = "Unknown", Text = "I need to be rubbing elbows, not working your fork", NumberOfWords = 10 },
        new Quote { QuoteId = 167, Speaker = "Buster", Text = "The ocean is my second biggest fear", NumberOfWords = 7 },
        new Quote { QuoteId = 168, Speaker = "Lindsay", Text = "I hope that's not a crack about my hair color, lips, forehead, nose and teeth because at least I'm not the wearing a round sweater set on my face", NumberOfWords = 29 },
        new Quote { QuoteId = 169, Speaker = "Barry", Text = "You're looking at balls here", NumberOfWords = 5 },
        new Quote { QuoteId = 170, Speaker = "GeorgeMichael", Text = "I've seen the blood", NumberOfWords = 4 },
        new Quote { QuoteId = 171, Speaker = "Unknown", Text = "Imagine the impact if that had come on right when we turned on the TV", NumberOfWords = 15 },
        new Quote { QuoteId = 172, Speaker = "Unknown", Text = "Cool your Japanese jets", NumberOfWords = 4 },
        new Quote { QuoteId = 173, Speaker = "Michael", Text = "You forgot to say \"away\" again", NumberOfWords = 6 },
        new Quote { QuoteId = 174, Speaker = "GOB", Text = "Look at the beak on that bird", NumberOfWords = 7 },
        new Quote { QuoteId = 175, Speaker = "Tobias", Text = "I think the name Michael is making you look for a man", NumberOfWords = 12 },
        new Quote { QuoteId = 176, Speaker = "Michael", Text = "You can just say \"intercourse\"", NumberOfWords = 5 },
        new Quote { QuoteId = 177, Speaker = "Michael", Text = "We just say \"manager\"", NumberOfWords = 4 },
        new Quote { QuoteId = 178, Speaker = "Michael", Text = "Doesn't matter who", NumberOfWords = 3 },
        new Quote { QuoteId = 179, Speaker = "Lucille", Text = "I'd rather be dead in California than alive in Arizona", NumberOfWords = 10 },
        new Quote { QuoteId = 180, Speaker = "Lindsay", Text = "I call it hot ham water", NumberOfWords = 6 },
        new Quote { QuoteId = 181, Speaker = "Tobias", Text = "He's a regular Freddie Wilson, that one", NumberOfWords = 7 },
        new Quote { QuoteId = 182, Speaker = "Michael", Text = "Don't call it that", NumberOfWords = 4 },
        new Quote { QuoteId = 183, Speaker = "Unknown", Text = "If you didn't have adult onset diabetes, I wouldn't mind giving you a little sugar", NumberOfWords = 15 },
        new Quote { QuoteId = 184, Speaker = "GOB", Text = "You don't want a hungry dove down your pants", NumberOfWords = 9 },
        new Quote { QuoteId = 186, Speaker = "GOB", Text = "Why go to a banana stand when we can make YOUR banana stand?", NumberOfWords = 13 },
        new Quote { QuoteId = 187, Speaker = "GOB", Text = "Don't worry, these young beauties have been nowhere near the bananas", NumberOfWords = 11 },
        new Quote { QuoteId = 188, Speaker = "GeorgeSenior", Text = "And that's why you don't try to teach lessons to your father", NumberOfWords = 12 },
        new Quote { QuoteId = 189, Speaker = "Unknown", Text = "We'll be the laughing stock of the boardwalk", NumberOfWords = 8 },
        new Quote { QuoteId = 190, Speaker = "GOB", Text = "If you feel something moving down there, it's just the bird", NumberOfWords = 11 },
        new Quote { QuoteId = 191, Speaker = "Unknown", Text = "I might have you beaten with a pillowcase full of batteries", NumberOfWords = 11 },
        new Quote { QuoteId = 193, Speaker = "Michael", Text = "Who's the \"her\" in that sentence?", NumberOfWords = 6 },
        new Quote { QuoteId = 194, Speaker = "Michael", Text = "Please don't call yourself that", NumberOfWords = 5 },
        new Quote { QuoteId = 195, Speaker = "Unknown", Text = "I don't know why I always assume that everyone has read my screenplay", NumberOfWords = 13 },
        new Quote { QuoteId = 196, Speaker = "GOB", Text = "I'm not going to spend this kind of money and not watch", NumberOfWords = 12 },
        new Quote { QuoteId = 197, Speaker = "GOB", Text = "He showers her with club sauce", NumberOfWords = 6 },
        new Quote { QuoteId = 198, Speaker = "Michael", Text = "You've never told me how many houses there are in the British Parliament", NumberOfWords = 13 },
        new Quote { QuoteId = 200, Speaker = "Tobias", Text = "You're blowing my mind, Frank", NumberOfWords = 5 },
        new Quote { QuoteId = 201, Speaker = "Tobias", Text = "The whole backside has moles", NumberOfWords = 5 },
        new Quote { QuoteId = 202, Speaker = "Tobias", Text = "There's no \"I\" in \"win\"", NumberOfWords = 5 },
        new Quote { QuoteId = 203, Speaker = "Tobias", Text = "Within her lies a queen", NumberOfWords = 5 },
        new Quote { QuoteId = 204, Speaker = "Unknown", Text = "You can control your bladder when you're dead", NumberOfWords = 8 },
        new Quote { QuoteId = 206, Speaker = "BobLoblaw", Text = "Why should you go to jail for a crime someone else noticed?", NumberOfWords = 12 },
        new Quote { QuoteId = 209, Speaker = "Unknown", Text = "I shall drop you off alive, hooker or no", NumberOfWords = 9 },
        new Quote { QuoteId = 210, Speaker = "Unknown", Text = "They're polite and the men all sound gay, but they will rip out your heart", NumberOfWords = 15 },
        new Quote { QuoteId = 211, Speaker = "Michael", Text = "I almost had Pop-Pop in Reno", NumberOfWords = 6 },
        new Quote { QuoteId = 212, Speaker = "Tobias", Text = "If this tableau I recreate, perhaps I can re-snare my mate", NumberOfWords = 11 },
        new Quote { QuoteId = 213, Speaker = "Unknown", Text = "I don't want anybody to go inside that musty claptrap", NumberOfWords = 10 },
        new Quote { QuoteId = 214, Speaker = "GOB", Text = "We were both waiting for our dads at that garden where the little boy found the arm", NumberOfWords = 17 },
        new Quote { QuoteId = 215, Speaker = "GOB", Text = "I kind of feel like that kid who found the severed hand", NumberOfWords = 12 },
        new Quote { QuoteId = 216, Speaker = "GOB", Text = "I don't see you crying, robot", NumberOfWords = 6 },
        new Quote { QuoteId = 217, Speaker = "Kitty", Text = "Say goodbye to these", NumberOfWords = 4 },
        new Quote { QuoteId = 218, Speaker = "Unknown", Text = "I promised myself I wasn't going to become one of those people who were always going on about their screenplays", NumberOfWords = 20 },
        new Quote { QuoteId = 220, Speaker = "Oscar", Text = "You haven't seen a little box with a turtle on it, have you?", NumberOfWords = 13 },
        new Quote { QuoteId = 221, Speaker = "Buster", Text = "My turtle was living in it before he ate all the grass and died", NumberOfWords = 14 },
        new Quote { QuoteId = 222, Speaker = "Tobias", Text = "The scabs come right off", NumberOfWords = 5 },
        new Quote { QuoteId = 223, Speaker = "Unknown", Text = "I can't say no to the woman who gave me chlamydia", NumberOfWords = 11 },
        new Quote { QuoteId = 224, Speaker = "Tobias", Text = "People hear the name Tobias, they think big black guy", NumberOfWords = 10 },
        new Quote { QuoteId = 225, Speaker = "GOB", Text = "I just don't want people's kids getting their sticky little fingers all over these $2,600 pants", NumberOfWords = 16 },
        new Quote { QuoteId = 226, Speaker = "GOB", Text = "The guy who's dirty dancing with his niece is going to tell the guy in the $3,600 suit how to run the business. Come on", NumberOfWords = 25 },
        new Quote { QuoteId = 227, Speaker = "Lucille", Text = "Suddenly playing with yourself is a scholarly pursuit", NumberOfWords = 8 },
        new Quote { QuoteId = 228, Speaker = "Lucille", Text = "If I wanted something your thumb touched, I'd eat the inside of your ear", NumberOfWords = 14 },
        new Quote { QuoteId = 229, Speaker = "Lucille", Text = "You let him go in the sun?", NumberOfWords = 7 },
        new Quote { QuoteId = 230, Speaker = "Unknown", Text = "Then why don't you marry an ice cream sandwich?", NumberOfWords = 9 },
        new Quote { QuoteId = 231, Speaker = "Tobias", Text = "I will pack your sweet pink mouth with so much ice cream you'll be the envy of every Jerry and Jane on the block", NumberOfWords = 24 },
        new Quote { QuoteId = 232, Speaker = "GeorgeSenior", Text = "I am having a love affair with this ice cream sandwich", NumberOfWords = 11 },
        new Quote { QuoteId = 233, Speaker = "GeorgeSenior", Text = "Did you stick it to her?", NumberOfWords = 6 },
        new Quote { QuoteId = 234, Speaker = "GeorgeSenior", Text = "Pop-Pop needs your hair", NumberOfWords = 4 },
        new Quote { QuoteId = 235, Speaker = "Unknown", Text = "At least he's in prison, not an urn", NumberOfWords = 8 },
        new Quote { QuoteId = 236, Speaker = "Unknown", Text = "You know the hair that no one's supposed to see?", NumberOfWords = 10 },
        new Quote { QuoteId = 237, Speaker = "Unknown", Text = "Everyone put on white robes and outsmarted us", NumberOfWords = 8 },
        new Quote { QuoteId = 238, Speaker = "Tobias", Text = "We shan't be telling your mother about this, shan't we?", NumberOfWords = 10 },
        new Quote { QuoteId = 239, Speaker = "Unknown", Text = "Now there's somebody who needs a good mother", NumberOfWords = 8 },
        new Quote { QuoteId = 240, Speaker = "Lucille", Text = "I'll leave when I'm good and ready", NumberOfWords = 7 },
        new Quote { QuoteId = 241, Speaker = "Maeby", Text = "I need one of those necklaces in the shape of a T", NumberOfWords = 12 },
        new Quote { QuoteId = 242, Speaker = "Lindsay", Text = "There's a cream with real diamonds in it", NumberOfWords = 8 },
        new Quote { QuoteId = 243, Speaker = "Tobias", Text = "You, sir, are a mouthful", NumberOfWords = 5 },
        new Quote { QuoteId = 244, Speaker = "GOB", Text = "If I can't find a horny immigrant by then, I don't deserve to stay here", NumberOfWords = 15 },
        new Quote { QuoteId = 245, Speaker = "Tobias", Text = "There's a man inside me, and only when he's finally out can I walk free of pain", NumberOfWords = 17 },
        new Quote { QuoteId = 246, Speaker = "Tobias", Text = "I'm afraid I prematurely shot my wad on what was supposed to be a \"dry run\", if you will, so now I'm afraid I have something of a mess on my hands", NumberOfWords = 32 },
        new Quote { QuoteId = 247, Speaker = "GOB", Text = "I've made a huge mistake", NumberOfWords = 5 },
        new Quote { QuoteId = 249, Speaker = "GeorgeMichael", Text = "I can't go on a million bike rides whenever you want me to", NumberOfWords = 13 },
        new Quote { QuoteId = 250, Speaker = "Unknown", Text = "The doctor said there were claw marks on the walls of her uterus", NumberOfWords = 13 },
        new Quote { QuoteId = 251, Speaker = "Buster", Text = "It's like she gets off on being withholding", NumberOfWords = 8 },
        new Quote { QuoteId = 252, Speaker = "GOB", Text = "Look who's ragging on the old lady", NumberOfWords = 7 },
        new Quote { QuoteId = 253, Speaker = "Lucille", Text = "Look at me, \"getting off\"", NumberOfWords = 5 },
        new Quote { QuoteId = 254, Speaker = "Unknown", Text = "I always ended up on all fours", NumberOfWords = 7 },
        new Quote { QuoteId = 255, Speaker = "Tobias", Text = "This kind of agility?", NumberOfWords = 4 },
        new Quote { QuoteId = 256, Speaker = "Tobias", Text = "Do you see me more as the respected dramatic actor or more of the beloved comic actor?", NumberOfWords = 17 },
        new Quote { QuoteId = 257, Speaker = "GOB", Text = "I don't even want to tell you what she wouldn't let me do to her in the car", NumberOfWords = 18 },
        new Quote { QuoteId = 258, Speaker = "Buster", Text = "I thought you had class", NumberOfWords = 5 },
        new Quote { QuoteId = 259, Speaker = "Tobias", Text = "Carl Weathers took everything from me", NumberOfWords = 6 },
        new Quote { QuoteId = 260, Speaker = "Tobias", Text = "You could have been sleeping with Frightened Inmate #2", NumberOfWords = 9 },
        new Quote { QuoteId = 261, Speaker = "GeorgeMichael", Text = "Some call me The Human Metronome", NumberOfWords = 6 },
        new Quote { QuoteId = 262, Speaker = "GOB", Text = "So far it's been all chain and no ball", NumberOfWords = 9 },
        new Quote { QuoteId = 263, Speaker = "Unknown", Text = "Not everything is strippers and booze and buckets of blood", NumberOfWords = 10 },
        new Quote { QuoteId = 264, Speaker = "Unknown", Text = "You're out of the band", NumberOfWords = 5 },
        new Quote { QuoteId = 265, Speaker = "Buster", Text = "I've already got a Lucille in my life", NumberOfWords = 8 },
        new Quote { QuoteId = 266, Speaker = "Buster", Text = "Is this something society will allow?", NumberOfWords = 6 },
        new Quote { QuoteId = 267, Speaker = "Buster", Text = "I just jumped through a plate glass window on a date", NumberOfWords = 11 },
        new Quote { QuoteId = 268, Speaker = "Kitty", Text = "I have been Googling your father", NumberOfWords = 6 },
        new Quote { QuoteId = 269, Speaker = "GeorgeSenior", Text = "I sold you for a pack of cigarettes", NumberOfWords = 8 },
        new Quote { QuoteId = 270, Speaker = "GeorgeSenior", Text = "You don't fire crazy", NumberOfWords = 4 },
        new Quote { QuoteId = 271, Speaker = "GeorgeSenior", Text = "All these books are cooked", NumberOfWords = 5 },
        new Quote { QuoteId = 272, Speaker = "GeorgeMichael", Text = "It's like a mind puzzle, an awesome mind puzzle", NumberOfWords = 9 },
        new Quote { QuoteId = 273, Speaker = "GeorgeMichael", Text = "Talk you off of what, Pop-Pop?", NumberOfWords = 6 },
        new Quote { QuoteId = 274, Speaker = "GOB", Text = "Where once there was a yacht, now there is naught", NumberOfWords = 10 },
        new Quote { QuoteId = 276, Speaker = "GeorgeMichael", Text = "I was going to smoke the marijuana like a cigarette", NumberOfWords = 10 },
        new Quote { QuoteId = 277, Speaker = "Lucille", Text = "They don't allow you to have bees in here", NumberOfWords = 9 },
        new Quote { QuoteId = 278, Speaker = "Barry", Text = "I think something laid eggs on me", NumberOfWords = 7 },
        new Quote { QuoteId = 279, Speaker = "Annyong", Text = "Mother say no carbohydrate for you if you ever going to get girlfriend that's not old lady", NumberOfWords = 17 },
        new Quote { QuoteId = 280, Speaker = "Annyong", Text = "Maybe we should kiss again to teach them a lesson about obvious", NumberOfWords = 12 },
        new Quote { QuoteId = 281, Speaker = "Lucille", Text = "Look how he zips now", NumberOfWords = 5 },
        new Quote { QuoteId = 282, Speaker = "Michael", Text = "I should have never taken the pumps out of here", NumberOfWords = 10 },
        new Quote { QuoteId = 284, Speaker = "CarlWeathers", Text = "Did you know that you can get a refill on any drink you want here, and it's free?", NumberOfWords = 18 },
        new Quote { QuoteId = 285, Speaker = "Lucille", Text = "Aren't you the sweetest thing, spending some time with what's left of your uncle", NumberOfWords = 14 },
        new Quote { QuoteId = 286, Speaker = "Buster", Text = "He couldn't wait to swoop in and throw on the sailor suit", NumberOfWords = 12 },
        new Quote { QuoteId = 287, Speaker = "Franklin", Text = "I got children all over town", NumberOfWords = 6 },
        new Quote { QuoteId = 288, Speaker = "Buster", Text = "My father is my uncle", NumberOfWords = 5 },
        new Quote { QuoteId = 289, Speaker = "GOB", Text = "That's the exact kind of joke he would have loved", NumberOfWords = 9 },
        new Quote { QuoteId = 290, Speaker = "Tobias", Text = "Who'd like a banger in the mouth?", NumberOfWords = 7 },
        new Quote { QuoteId = 291, Speaker = "Michael", Text = "We just call it a sausage", NumberOfWords = 6 },
        new Quote { QuoteId = 292, Speaker = "GOB", Text = "Franklin said some things Whitey just wasn't ready to hear", NumberOfWords = 10 },
        new Quote { QuoteId = 293, Speaker = "Tobias", Text = "I forgot that we were in the colonies", NumberOfWords = 8 },
        new Quote { QuoteId = 295, Speaker = "GOB", Text = "My socks are wet", NumberOfWords = 4 },
        new Quote { QuoteId = 296, Speaker = "GOB", Text = "Me quick, want slow", NumberOfWords = 4 },
        new Quote { QuoteId = 298, Speaker = "Tobias", Text = "I'd want to get in there and find some answers", NumberOfWords = 10 },
        new Quote { QuoteId = 299, Speaker = "Tobias", Text = "Excuse me for liking the way they shape my junk", NumberOfWords = 10 },
        new Quote { QuoteId = 300, Speaker = "Ann", Text = "It's not just going to be my love and George Michael's, but God's love as well", NumberOfWords = 16 },
        new Quote { QuoteId = 301, Speaker = "GeorgeMichael", Text = "Can it open a can?", NumberOfWords = 5 },
        new Quote { QuoteId = 302, Speaker = "Buster", Text = "A seal didn't bite your Linus off, right?", NumberOfWords = 8 },
        new Quote { QuoteId = 303, Speaker = "Michael", Text = "No, a seal didn't bite my Linus off", NumberOfWords = 8 },
        new Quote { QuoteId = 304, Speaker = "GeorgeSenior", Text = "Up yours, granny!", NumberOfWords = 3 },
        new Quote { QuoteId = 305, Speaker = "Lucille", Text = "You couldn't handle it!", NumberOfWords = 4 },
        new Quote { QuoteId = 306, Speaker = "Tobias", Text = "Seems like only yesterday you were bursting forth from your mother's fertile womb", NumberOfWords = 13 },
        new Quote { QuoteId = 307, Speaker = "Maeby", Text = "You don't see me nervous about being on my third Virgin Mary", NumberOfWords = 12 },
        new Quote { QuoteId = 308, Speaker = "Lucille", Text = "You are a worse psychiatrist than you are a son-in-law, and you will never get work as an actor because you have no talent", NumberOfWords = 24 },
        new Quote { QuoteId = 309, Speaker = "Tobias", Text = "I had no idea a ninety year-old man could cave in my chest cavity like that", NumberOfWords = 16 },
        new Quote { QuoteId = 310, Speaker = "Tobias", Text = "I think your knee is on my heart", NumberOfWords = 8 },
        new Quote { QuoteId = 312, Speaker = "Lindsay", Text = "I'm going to see if I can get a wrench to strip my nuts", NumberOfWords = 14 },
        new Quote { QuoteId = 313, Speaker = "GeorgeSenior", Text = "I haven't had a massage since prison", NumberOfWords = 7 },
        new Quote { QuoteId = 314, Speaker = "Lucille", Text = "He's an alpaca", NumberOfWords = 3 },
        new Quote { QuoteId = 315, Speaker = "GOB", Text = "One of this guy's eyebrows just fell in the bowl of candy beans", NumberOfWords = 13 },
        new Quote { QuoteId = 316, Speaker = "Michael", Text = "I think George Michael is hiding Ann in the attic", NumberOfWords = 10 },
        new Quote { QuoteId = 317, Speaker = "Michael", Text = "It's as Ann as the nose on Plain's face", NumberOfWords = 9 },
        new Quote { QuoteId = 318, Speaker = "GeorgeMichael", Text = "I have Pop-Pop in the attic", NumberOfWords = 6 },
        new Quote { QuoteId = 319, Speaker = "Tobias", Text = "Who wants to go to the hospital?", NumberOfWords = 7 },
        new Quote { QuoteId = 320, Speaker = "Tobias", Text = "That was 100% inappropriate, and I do apologize profusely", NumberOfWords = 9 },
        new Quote { QuoteId = 321, Speaker = "Buster", Text = "I ought to point to Uncle Oscar's Charlie Browns next time you're on top of him, Mother", NumberOfWords = 17 },
        new Quote { QuoteId = 322, Speaker = "Tobias", Text = "I figured if I blue myself early I'd be nice and relaxed for a 9:00 dinner reservation", NumberOfWords = 17 },
        new Quote { QuoteId = 323, Speaker = "Lindsay", Text = "I can actually smear diamonds on my face, and it's only $400 a tub", NumberOfWords = 14 },
        new Quote { QuoteId = 324, Speaker = "GeorgeMichael", Text = "She calls it a 'mayon-egg'", NumberOfWords = 5 },
        new Quote { QuoteId = 325, Speaker = "Buster", Text = "Mom volunteered me for the Army just because the fat man dared her to", NumberOfWords = 14 },
        new Quote { QuoteId = 326, Speaker = "GOB", Text = "The tears just aren't coming", NumberOfWords = 5 },
        new Quote { QuoteId = 327, Speaker = "Buster", Text = "You mean you can wear stripper clothes when you're not stripping?", NumberOfWords = 11 },
        new Quote { QuoteId = 328, Speaker = "GeorgeSenior", Text = "You could hump that hood", NumberOfWords = 5 },
        new Quote { QuoteId = 329, Speaker = "GeorgeMichael", Text = "What a fun sexy time for you", NumberOfWords = 7 },
        new Quote { QuoteId = 330, Speaker = "Warden", Text = "What I'm calling you is a television actor", NumberOfWords = 8 },
        new Quote { QuoteId = 331, Speaker = "Warden", Text = "There's only one man I've ever called a coward, and that's Brian Doyle Murray", NumberOfWords = 14 },
        new Quote { QuoteId = 332, Speaker = "GeorgeSenior", Text = "We do not wag our genitals at one another to make a point", NumberOfWords = 13 },
        new Quote { QuoteId = 333, Speaker = "GOB", Text = "It's a mainstay of the magician's toolkit, like how clowns always have a rag soaked in ether", NumberOfWords = 17 },
        new Quote { QuoteId = 334, Speaker = "GOB", Text = "The worst that could happen is that I could spill coffee all over this $3,000 suit", NumberOfWords = 16 },
        new Quote { QuoteId = 336, Speaker = "Michael", Text = "I liked it better when he just said Annyong", NumberOfWords = 9 },
        new Quote { QuoteId = 337, Speaker = "GeorgeSenior", Text = "Maybe it was the eleven months he spent in the womb", NumberOfWords = 11 },
        new Quote { QuoteId = 338, Speaker = "Lindsay", Text = "You don\'t cry when you take those off?", NumberOfWords = 8 },
        new Quote { QuoteId = 339, Speaker = "GeorgeSenior", Text = "How many times I gotta tell this kid chicken wings?", NumberOfWords = 10 },
        new Quote { QuoteId = 340, Speaker = "Tobias", Text = "Somebody is a rude Gus", NumberOfWords = 5 },
        new Quote { QuoteId = 341, Speaker = "GOB", Text = "I can't even fake the death of a stripper", NumberOfWords = 9 },
        new Quote { QuoteId = 342, Speaker = "GOB", Text = "You didn't eat that dove, did you?", NumberOfWords = 7 },
        new Quote { QuoteId = 343, Speaker = "GeorgeSenior", Text = "If someone had left a note, this innocent man would still have his arm", NumberOfWords = 14 },
        new Quote { QuoteId = 344, Speaker = "Lucille", Text = "You'd think a man locked up in prison would able to abstain", NumberOfWords = 12 },
        new Quote { QuoteId = 345, Speaker = "Lucille", Text = "Your father with his disgusting tweaking", NumberOfWords = 6 },
        new Quote { QuoteId = 346, Speaker = "Lucille", Text = "I couldn't breast feed any of you kids because of that man", NumberOfWords = 12 },
        new Quote { QuoteId = 347, Speaker = "Michael", Text = "This is the nicest she's been since she found out that Rosa could breast-feed Buster", NumberOfWords = 15 },
        new Quote { QuoteId = 348, Speaker = "GOB", Text = "First you dump all over it, now you want to know how it's done", NumberOfWords = 14 },
        new Quote { QuoteId = 349, Speaker = "Tobias", Text = "I feel like the prettiest girl at the dance", NumberOfWords = 9 },
        new Quote { QuoteId = 350, Speaker = "Tobias", Text = "I need to go take down the buffet and set up the leather pony", NumberOfWords = 14 },
        new Quote { QuoteId = 351, Speaker = "GeorgeSenior", Text = "They cannot arrest a husband and wife for the same crime", NumberOfWords = 11 },
        new Quote { QuoteId = 352, Speaker = "GeorgeMichael", Text = "Say what you want about America - thirteen bucks can still get you a hell of a lot of mice", NumberOfWords = 20 },
        new Quote { QuoteId = 353, Speaker = "GOB", Text = "Who said anything bad about America?", NumberOfWords = 6 },
        new Quote { QuoteId = 354, Speaker = "GeorgeMichael", Text = "So I'm thinking of getting a motorcycle", NumberOfWords = 7 },
        new Quote { QuoteId = 355, Speaker = "Maeby", Text = "Your legs look exactly like mine, and I just shaved mine", NumberOfWords = 11 },
        new Quote { QuoteId = 356, Speaker = "Tobias", Text = "I'm looking for something that says \"Dad likes leather\"", NumberOfWords = 9 },
        new Quote { QuoteId = 357, Speaker = "Tobias", Text = "You have to be some sort of she-hulk to get this", NumberOfWords = 11 },
        new Quote { QuoteId = 358, Speaker = "Buster", Text = "Mom, you're ruining our fort", NumberOfWords = 5 },
        new Quote { QuoteId = 359, Speaker = "Tobias", Text = "Who'd want to mess with any of us?", NumberOfWords = 8 },
        new Quote { QuoteId = 360, Speaker = "GeorgeMichael", Text = "Trying to introduce some edge to the whole palette", NumberOfWords = 9 },
        new Quote { QuoteId = 361, Speaker = "Lucille", Text = "Is she the one who's going to take him to the dentist?", NumberOfWords = 12 },
        new Quote { QuoteId = 362, Speaker = "UncleJack", Text = "You're right inside me now", NumberOfWords = 5 },
        new Quote { QuoteId = 363, Speaker = "Unknown", Text = "I can't believe they wouldn't even give me a wheelchair ride", NumberOfWords = 11 },
        new Quote { QuoteId = 364, Speaker = "Buster", Text = "Doesn't this make you want to have an ice-cream cone?", NumberOfWords = 10 },
        new Quote { QuoteId = 365, Speaker = "Buster", Text = "I do believe there was some mention of some ice cream", NumberOfWords = 11 },
        new Quote { QuoteId = 366, Speaker = "Buster", Text = "Does anyone know how to eat one of these?", NumberOfWords = 9 },
        new Quote { QuoteId = 367, Speaker = "Tobias", Text = "There's a new daddy in town. A discipline daddy.", NumberOfWords = 9 },
        new Quote { QuoteId = 368, Speaker = "Buster", Text = "I tried hitchhiking, but it's hard to do without a thumb", NumberOfWords = 11 },
        new Quote { QuoteId = 369, Speaker = "Tobias", Text = "Now what we do is we paint our lips Joan Crawford red, pop on a little blue eyeliner and then plant a lipstick kiss on every one of them", NumberOfWords = 29 },
        new Quote { QuoteId = 370, Speaker = "GOB", Text = "Still, where'd the lighter fluid come from?", NumberOfWords = 7 },
        new Quote { QuoteId = 371, Speaker = "GeorgeSenior", Text = "Larry, go to a mirror", NumberOfWords = 5 },
        new Quote { QuoteId = 372, Speaker = "Tobias", Text = "Why am I not going under water?", NumberOfWords = 7 },
        new Quote { QuoteId = 373, Speaker = "JudgeReinhold", Text = "Why did I lose all the weight if they're going to put me in a pool cover?", NumberOfWords = 17 },
        new Quote { QuoteId = 374, Speaker = "GeorgeMichael", Text = "I wish I could draw her nose", NumberOfWords = 7 },
        new Quote { QuoteId = 375, Speaker = "Tobias", Text = "I just found out that my cellular telephone was a lemon", NumberOfWords = 11 },
        new Quote { QuoteId = 376, Speaker = "Michael", Text = "Are you wearing my dead wife's maternity clothes?", NumberOfWords = 8 },
        new Quote { QuoteId = 377, Speaker = "Unknown", Text = "I can't get this ham open", NumberOfWords = 6 },
        new Quote { QuoteId = 378, Speaker = "Tobias", Text = "If he's got a shot with her, just give me a little tap on the fanny", NumberOfWords = 16 },
        new Quote { QuoteId = 379, Speaker = "GOB", Text = "Now, when you do this without getting punched in the chest, you'll have more fun", NumberOfWords = 15 },
        new Quote { QuoteId = 380, Speaker = "Tobias", Text = "The Blue Man Group might need me, and I do deserve a fancy phone", NumberOfWords = 14 },
        new Quote { QuoteId = 381, Speaker = "Unknown", Text = "The doctor said I couldn't be a mother now if I tried", NumberOfWords = 12 },
        new Quote { QuoteId = 382, Speaker = "Lindsay", Text = "I'm much, much, much older than 15", NumberOfWords = 7 },
        new Quote { QuoteId = 383, Speaker = "Unknown", Text = "And the worst part is he thinks he's passing", NumberOfWords = 9 },
        new Quote { QuoteId = 384, Speaker = "Unknown", Text = "Wow, that does sound like a little girl", NumberOfWords = 8 },
        new Quote { QuoteId = 385, Speaker = "Barry", Text = "I'm going for a hot Ding Dong", NumberOfWords = 7 },
        new Quote { QuoteId = 386, Speaker = "Lindsay", Text = "She said “tingling” like 75 times", NumberOfWords = 6 },
        new Quote { QuoteId = 387, Speaker = "Unknown", Text = "You smell like a pine cone", NumberOfWords = 6 },
        new Quote { QuoteId = 388, Speaker = "Unknown", Text = "I'm on bad mushrooms", NumberOfWords = 4 },
        new Quote { QuoteId = 389, Speaker = "Barry", Text = "This close, they always look like landscape", NumberOfWords = 7 },
        new Quote { QuoteId = 390, Speaker = "Unknown", Text = "There were cutoffs up here?", NumberOfWords = 5 },
        new Quote { QuoteId = 391, Speaker = "Unknown", Text = "What are you doing with Mother's rape horn?", NumberOfWords = 8 },
        new Quote { QuoteId = 392, Speaker = "Unknown", Text = "Do you want to steer, or are you too old to sit on your pop's lap and drive?", NumberOfWords = 18 },
        new Quote { QuoteId = 393, Speaker = "Unknown", Text = "They impounded my humble trailer", NumberOfWords = 5 },
        new Quote { QuoteId = 394, Speaker = "Unknown", Text = "Does this look contagious to you?", NumberOfWords = 6 },
        new Quote { QuoteId = 395, Speaker = "Unknown", Text = "Nice to be back in a queen", NumberOfWords = 7 },
        new Quote { QuoteId = 396, Speaker = "Unknown", Text = "Let the great experiment begin", NumberOfWords = 5 },
        new Quote { QuoteId = 397, Speaker = "Unknown", Text = "There's got to be a better way to say that", NumberOfWords = 10 },
        new Quote { QuoteId = 398, Speaker = "Unknown", Text = "I am having the time of my life", NumberOfWords = 8 },
        new Quote { QuoteId = 399, Speaker = "Unknown", Text = "I haven't met Ann", NumberOfWords = 4 },
        new Quote { QuoteId = 400, Speaker = "Unknown", Text = "I kind of want to buy her a diamond", NumberOfWords = 9 },
        new Quote { QuoteId = 401, Speaker = "Unknown", Text = "I'm sure that Egg is a very nice person", NumberOfWords = 9 },
        new Quote { QuoteId = 402, Speaker = "Unknown", Text = "I heard zoo noises", NumberOfWords = 4 },
        new Quote { QuoteId = 403, Speaker = "Unknown", Text = "Which pinky do you use less?", NumberOfWords = 6 },
        new Quote { QuoteId = 404, Speaker = "Unknown", Text = "Nothing on the inside", NumberOfWords = 4 },
        new Quote { QuoteId = 405, Speaker = "Unknown", Text = "I'm not proud of the way I was so grossed out when I found out you were gross before", NumberOfWords = 19 },
        new Quote { QuoteId = 406, Speaker = "Unknown", Text = "I'm just hoping to get mildly injured so I can get out of the Army", NumberOfWords = 15 },
        new Quote { QuoteId = 407, Speaker = "Unknown", Text = "I think my nipples are bleeding", NumberOfWords = 6 },
        new Quote { QuoteId = 408, Speaker = "Unknown", Text = "Flashes of Quincy", NumberOfWords = 3 },
        new Quote { QuoteId = 409, Speaker = "Unknown", Text = "I think the plant lady's wearing a thong", NumberOfWords = 8 },
        new Quote { QuoteId = 410, Speaker = "Unknown", Text = "Don't be such an Ann hog", NumberOfWords = 6 },
        new Quote { QuoteId = 411, Speaker = "Unknown", Text = "Go see a Star War", NumberOfWords = 5 },
        new Quote { QuoteId = 412, Speaker = "Unknown", Text = "Why am I not blacking out?", NumberOfWords = 6 },
        new Quote { QuoteId = 413, Speaker = "Unknown", Text = "He swore by that Glisten", NumberOfWords = 5 },
        new Quote { QuoteId = 414, Speaker = "Unknown", Text = "Let's go dig up your uncle", NumberOfWords = 6 },
        new Quote { QuoteId = 415, Speaker = "Tobias", Text = "I will be head to toe in blue makeup until 8:01 in case the Blue Man Group needs their understudy", NumberOfWords = 20 },
        new Quote { QuoteId = 416, Speaker = "Unknown", Text = "Are we having yams?", NumberOfWords = 4 },
        new Quote { QuoteId = 418, Speaker = "Unknown", Text = "I don't think we need people trying to compete with what I'm wearing", NumberOfWords = 13 },
        new Quote { QuoteId = 419, Speaker = "Unknown", Text = "Don't ask me, I'm just the boy's father", NumberOfWords = 8 },
        new Quote { QuoteId = 420, Speaker = "Lucille", Text = "No one would believe that a woman like me would have a gay son", NumberOfWords = 14 },
        new Quote { QuoteId = 421, Speaker = "GeorgeMichael", Text = "I can see marinating a chicken in that", NumberOfWords = 8 },
        new Quote { QuoteId = 422, Speaker = "GeorgeSenior", Text = "Your Tweety Bird dance just cost us a run, you moron", NumberOfWords = 11 },
        new Quote { QuoteId = 423, Speaker = "GOB", Text = "How do we filter out the teases? We don't let them in.", NumberOfWords = 12 },
        new Quote { QuoteId = 424, Speaker = "Lucille2", Text = "I am stable as a table", NumberOfWords = 6 },
        new Quote { QuoteId = 425, Speaker = "Buster", Text = "I would hardly call my mother a girl, but yes, she's still very much a part of my life", NumberOfWords = 19 },
        new Quote { QuoteId = 426, Speaker = "Lucille2", Text = "Everybody thinks they're Frank Sinatra", NumberOfWords = 5 },
        new Quote { QuoteId = 427, Speaker = "GOB", Text = "They make me feel dressier", NumberOfWords = 5 },
        new Quote { QuoteId = 428, Speaker = "Unknown", Text = "A piano could stand on those legs", NumberOfWords = 7 },
        new Quote { QuoteId = 429, Speaker = "GeorgeMichael", Text = "Guess she didn't see the drawings", NumberOfWords = 6 },
        new Quote { QuoteId = 430, Speaker = "Unknown", Text = "You have undone all of Dr. Sandor Plumb's work", NumberOfWords = 9 },
        new Quote { QuoteId = 431, Speaker = "Unknown", Text = "I need to prove to her that I'm not just a man, but a man's man", NumberOfWords = 16 },
        new Quote { QuoteId = 432, Speaker = "Unknown", Text = "Shall I put the Posturepedic in the down position?", NumberOfWords = 9 },
        new Quote { QuoteId = 433, Speaker = "Unknown", Text = "Read me the appetizers again", NumberOfWords = 5 },
        new Quote { QuoteId = 434, Speaker = "Unknown", Text = "Did you have too much club sauce on your calamari?", NumberOfWords = 10 },
        new Quote { QuoteId = 435, Speaker = "Unknown", Text = "I tried to drink some of the water, and it was too hot and it tasted like soy sauce", NumberOfWords = 19 },
        new Quote { QuoteId = 436, Speaker = "Unknown", Text = "I think the teriyaki chicken burst", NumberOfWords = 6 },
        new Quote { QuoteId = 437, Speaker = "Unknown", Text = "This isn't turning into the party hangout I hoped", NumberOfWords = 9 },
        new Quote { QuoteId = 438, Speaker = "Unknown", Text = "Stick a wrench in me, I'm done", NumberOfWords = 7 },
        new Quote { QuoteId = 439, Speaker = "Unknown", Text = "Someone order 140 pounds of upper-body strength?", NumberOfWords = 7 },
        new Quote { QuoteId = 440, Speaker = "Unknown", Text = "It's just something the body does when you shake it", NumberOfWords = 10 },
        new Quote { QuoteId = 441, Speaker = "Unknown", Text = "Well, I'm all grown up now", NumberOfWords = 6 },
        new Quote { QuoteId = 442, Speaker = "Unknown", Text = "How'd you like to take a nap, baldy?", NumberOfWords = 8 },
        new Quote { QuoteId = 443, Speaker = "Unknown", Text = "Let's not spin in the comfy chair", NumberOfWords = 7 },
        new Quote { QuoteId = 444, Speaker = "Unknown", Text = "I got Michael out of his marriage, didn't I?", NumberOfWords = 9 },
        new Quote { QuoteId = 445, Speaker = "Oscar", Text = "I need macaroons", NumberOfWords = 3 },
        new Quote { QuoteId = 446, Speaker = "Oscar", Text = "You can win every argument like that, but that does not make you right", NumberOfWords = 14 },
        new Quote { QuoteId = 447, Speaker = "Unknown", Text = "I really hate it when you put on the God costume", NumberOfWords = 11 },
        new Quote { QuoteId = 448, Speaker = "Buster", Text = "I'm cloaking myself in her scent", NumberOfWords = 6 },
        new Quote { QuoteId = 449, Speaker = "Buster", Text = "I was made to understand that there would be grilled cheese sandwiches here", NumberOfWords = 13 },
        new Quote { QuoteId = 450, Speaker = "Buster", Text = "Will someone please have the decency to punch me in the face?", NumberOfWords = 12 },
        new Quote { QuoteId = 451, Speaker = "Buster", Text = "Mom always taught us to curl up in a ball and remain motionless when confronted", NumberOfWords = 15 },
        new Quote { QuoteId = 452, Speaker = "Buster", Text = "We have unlimited juice?", NumberOfWords = 4 },
        new Quote { QuoteId = 454, Speaker = "Unknown", Text = "We all know you're Annyong", NumberOfWords = 5 },
        new Quote { QuoteId = 455, Speaker = "Buster", Text = "No, Mother, I can blow myself", NumberOfWords = 6 },
        new Quote { QuoteId = 456, Speaker = "Unknown", Text = "Her?", NumberOfWords = 1 },
        new Quote { QuoteId = 457, Speaker = "Unknown", Text = "She was made in a cup, like soup", NumberOfWords = 8 },
        new Quote { QuoteId = 458, Speaker = "Tobias", Text = "Oh, I'm sorry, I forgot: your wife is dead", NumberOfWords = 9 },
        new Quote { QuoteId = 459, Speaker = "Unknown", Text = "The one thing I will never do is not tell him that I'm taking him to a cabin in the woods and then not take him", NumberOfWords = 26 },
        new Quote { QuoteId = 460, Speaker = "Unknown", Text = "He was our miracle baby", NumberOfWords = 5 },
        new Quote { QuoteId = 461, Speaker = "Unknown", Text = "It's like my heart is getting hard", NumberOfWords = 7 },
        new Quote { QuoteId = 462, Speaker = "Unknown", Text = "I know what an erection feels like, Michael", NumberOfWords = 8 },
        new Quote { QuoteId = 463, Speaker = "Unknown", Text = "Those aren't even birds", NumberOfWords = 4 },
        new Quote { QuoteId = 464, Speaker = "Unknown", Text = "But I'm white", NumberOfWords = 3 },
        new Quote { QuoteId = 465, Speaker = "Unknown", Text = "It ain't easy being white", NumberOfWords = 5 },
        new Quote { QuoteId = 466, Speaker = "Unknown", Text = "I'm Mom and I want to shoot down everything you say so I feel good about myself", NumberOfWords = 17 },
        new Quote { QuoteId = 467, Speaker = "Unknown", Text = "Lets deal some drugs", NumberOfWords = 4 },
        new Quote { QuoteId = 468, Speaker = "Unknown", Text = "Why do you think I wear these?", NumberOfWords = 7 },
        new Quote { QuoteId = 469, Speaker = "Unknown", Text = "A magician never reveals his secrets", NumberOfWords = 6 },
        new Quote { QuoteId = 470, Speaker = "Unknown", Text = "When's that voice gonna drop?", NumberOfWords = 5 },
        new Quote { QuoteId = 471, Speaker = "Unknown", Text = "I'm gonna go get sexy", NumberOfWords = 5 },
        new Quote { QuoteId = 472, Speaker = "Unknown", Text = "They said he was some kind of scientist", NumberOfWords = 8 },
        new Quote { QuoteId = 473, Speaker = "Unknown", Text = "Speaking of settling, How's Ann?", NumberOfWords = 5 },
        new Quote { QuoteId = 474, Speaker = "Unknown", Text = "It's hard to gauge time", NumberOfWords = 5 },
        new Quote { QuoteId = 475, Speaker = "Unknown", Text = "I like the way they think", NumberOfWords = 6 },
        new Quote { QuoteId = 476, Speaker = "Unknown", Text = "I was hoping he would be gifted sexually", NumberOfWords = 8 },
        new Quote { QuoteId = 477, Speaker = "Unknown", Text = "If this were a Lifetime Moment of Truth movie, this would be our act break", NumberOfWords = 15 },
        new Quote { QuoteId = 478, Speaker = "Unknown", Text = "A flower in my garden, a mystery in my panties", NumberOfWords = 10 },
        new Quote { QuoteId = 479, Speaker = "Unknown", Text = "I'm a scholar. I enjoy scholarly pursuits", NumberOfWords = 7 },
        new Quote { QuoteId = 480, Speaker = "Unknown", Text = "The warden could easily be black", NumberOfWords = 6 },
        new Quote { QuoteId = 481, Speaker = "Unknown", Text = "Who is this shiny building of a man?", NumberOfWords = 8 },
        new Quote { QuoteId = 482, Speaker = "Unknown", Text = "Chickens don't clap", NumberOfWords = 3 },
        new Quote { QuoteId = 483, Speaker = "Unknown", Text = "I've got a stair car full of Mexican laborers that would love a day's work", NumberOfWords = 15 },
        new Quote { QuoteId = 484, Speaker = "Unknown", Text = "Are beads cheap?", NumberOfWords = 3 },
        new Quote { QuoteId = 485, Speaker = "Unknown", Text = "We'll see who brings in more honey", NumberOfWords = 7 },
        new Quote { QuoteId = 486, Speaker = "Unknown", Text = "He's thinking about bees again", NumberOfWords = 5 },
        new Quote { QuoteId = 487, Speaker = "Unknown", Text = "We're going to have to figure out something to do so that people can look at you without wanting to kill themselves", NumberOfWords = 22 },
        new Quote { QuoteId = 488, Speaker = "Unknown", Text = "You don’t know a good bird hospital, do you?", NumberOfWords = 9 }
      );
    }
  }
}